from __future__ import annotations


TEXT = {
    "zh": {
        "window_title": "TOPTICA DLC pro 控制台",
        "language": "语言",
        "connection": "连接",
        "mode": "连接方式",
        "network": "网络",
        "serial": "串口",
        "host": "主机/IP/系统标签",
        "serial_port": "串口设备",
        "baudrate": "波特率",
        "timeout": "超时 (s)",
        "connect": "连接",
        "disconnect": "断开",
        "refresh": "刷新参数",
        "connected": "已连接",
        "disconnected": "未连接",
        "busy": "处理中...",
        "device_parameters": "当前设备参数",
        "parameter": "参数",
        "value": "当前值",
        "workspace": "功能区",
        "laser": "激光",
        "scan_lock": "Scan&Lock",
        "relock": "Relock",
        "stabilization": "Stabilization",
        "placeholder_title": "预留页面",
        "placeholder_body": "这里预留给后续功能扩展。",
        "laser_page_title": "CC - 电流控制",
        "laser_page_subtitle": "激光控制",
        "current_control": "电流读取与控制",
        "current_set": "设定电流 (mA)",
        "current_act": "实际电流 (mA)",
        "current_clip": "最大电流限制 (mA)",
        "current_clip_tuning": "调谐限幅电流上限 (mA)",
        "current_clip_limit": "硬件电流上限 (mA)",
        "effective_current_max": "当前可写入最大电流 (mA)",
        "cc_status": "电流控制状态",
        "step_precision": "调节步进",
        "precision_target": "当前调节",
        "step_100": "100",
        "step_10": "10",
        "step_1_int": "1",
        "step_1": "0.1",
        "step_2": "0.01",
        "step_3": "0.001",
        "step_4": "0.0001",
        "step_5": "0.00001",
        "step_6": "0.000001",
        "auto_apply_hint": "修改设定电流后自动写入设备",
        "confirm_title": "确认快速调节",
        "confirm_apply_current": "本次将把设定电流从 {current:.5f} mA 调到 {value:.5f} mA，变化较大，确认继续吗？",
        "confirm_large_change_title": "确认参数写入",
        "confirm_large_change_body": "准备将 {label} 从 {current} 改为 {value}，确认继续吗？",
        "exit_confirm_title": "确认退出",
        "exit_confirm_body": "确定要关闭程序吗？",
        "connection_lost_title": "连接已断开",
        "safety_title": "安全提示",
        "safety_text": (
            "依据 Manual.md：带 MOTOR pro 的激光头在做 motor scan 前，"
            "应启用调谐限幅，避免损伤激光二极管。"
        ),
        "serial_ports": "可用串口",
        "network_adapters": "本机网卡",
        "not_available": "未安装或不可用",
        "latest_message": "最新系统消息",
        "emission": "系统发射",
        "interlock": "联锁打开",
        "cc_enabled": "CC 已启用",
        "cc_emission": "CC 发射状态",
        "enable": "启用",
        "disable": "禁用",
        "maximum_current": "最大电流",
        "feedforward": "前馈控制",
        "feedforward_factor": "前馈系数",
        "arc": "模拟远程控制",
        "arc_signal_input": "ARC 信号输入",
        "arc_factor": "ARC 系数",
        "temperature_control": "TC - 温度控制",
        "set_temperature": "设定温度",
        "actual_temperature": "实际温度",
        "temperature_unit": "°C",
        "tc_arc_factor_unit": "K/V",
        "piezo_control": "PC - 压电控制",
        "set_voltage": "设定电压",
        "actual_voltage": "实际电压",
        "voltage_unit": "V",
        "slew_rate_enable": "斜率限制启用",
        "slew_rate": "斜率限制",
        "slew_rate_unit": "V/s",
        "pc_arc_factor_unit": "V/V",
        "pressure_compensation": "气压补偿",
        "enabled_label": "启用",
        "air_pressure": "气压",
        "air_pressure_unit": "hPa",
        "pressure_comp_factor": "补偿系数",
        "pressure_comp_factor_unit": "V/hPa",
        "compensation_voltage": "补偿电压",
        "none": "无",
        "fine_in_1": "精细输入 1",
        "fine_in_2": "精细输入 2",
        "fast_in_3": "快速输入 3",
        "fast_in_4": "快速输入 4",
        "enabled_state": "已启用",
        "disabled_state": "已禁用",
        "arc_factor_unit": "mA/V",
        "feedforward_factor_unit": "mA/K 或 mA/V",
        "device_overview": "设备概览",
    },
    "en": {
        "window_title": "TOPTICA DLC pro Console",
        "language": "Language",
        "connection": "Connection",
        "mode": "Mode",
        "network": "Network",
        "serial": "Serial",
        "host": "Host/IP/System Label",
        "serial_port": "Serial Port",
        "baudrate": "Baudrate",
        "timeout": "Timeout (s)",
        "connect": "Connect",
        "disconnect": "Disconnect",
        "refresh": "Refresh",
        "connected": "Connected",
        "disconnected": "Disconnected",
        "busy": "Working...",
        "device_parameters": "Current Device Parameters",
        "parameter": "Parameter",
        "value": "Value",
        "workspace": "Workspace",
        "laser": "Laser",
        "scan_lock": "Scan&Lock",
        "relock": "Relock",
        "stabilization": "Stabilization",
        "placeholder_title": "Reserved Page",
        "placeholder_body": "This page is reserved for future expansion.",
        "laser_page_title": "CC - Current Control",
        "laser_page_subtitle": "Laser Control",
        "current_control": "Current Readback and Control",
        "current_set": "Set Current Iset (mA)",
        "current_act": "Actual Current Iact (mA)",
        "current_clip": "Current Clip (mA)",
        "current_clip_tuning": "Tuning Clip Current Max (mA)",
        "current_clip_limit": "Hardware Current Limit (mA)",
        "effective_current_max": "Current Writable Max (mA)",
        "cc_status": "Current Controller Status",
        "step_precision": "Adjustment Step",
        "precision_target": "Current Target",
        "step_100": "100",
        "step_10": "10",
        "step_1_int": "1",
        "step_1": "0.1",
        "step_2": "0.01",
        "step_3": "0.001",
        "step_4": "0.0001",
        "step_5": "0.00001",
        "step_6": "0.000001",
        "auto_apply_hint": "Set current is written automatically after adjustment",
        "confirm_title": "Confirm Fast Adjustment",
        "confirm_apply_current": "Change set current from {current:.5f} mA to {value:.5f} mA? This is a large adjustment.",
        "confirm_large_change_title": "Confirm Parameter Write",
        "confirm_large_change_body": "Change {label} from {current} to {value}?",
        "exit_confirm_title": "Confirm Exit",
        "exit_confirm_body": "Close the application?",
        "connection_lost_title": "Connection Lost",
        "safety_title": "Safety Note",
        "safety_text": (
            "Per Manual.md: for laser heads with MOTOR pro, enable Use Tuning Clip "
            "before a motor scan to avoid laser diode damage."
        ),
        "serial_ports": "Available Serial Ports",
        "network_adapters": "Local Network Adapters",
        "not_available": "Not installed or unavailable",
        "latest_message": "Latest System Message",
        "emission": "System Emission",
        "interlock": "Interlock Open",
        "cc_enabled": "CC Enabled",
        "cc_emission": "CC Emission",
        "enable": "Enable",
        "disable": "Disable",
        "maximum_current": "Maximum Current",
        "feedforward": "Feed Forward",
        "feedforward_factor": "Feed Forward Factor",
        "arc": "Analog Remote Control",
        "arc_signal_input": "ARC Signal Input",
        "arc_factor": "ARC Factor",
        "temperature_control": "TC - Temperature Control",
        "set_temperature": "Set Temperature",
        "actual_temperature": "Actual Temperature",
        "temperature_unit": "°C",
        "tc_arc_factor_unit": "K/V",
        "piezo_control": "PC - Piezo Control",
        "set_voltage": "Set Voltage",
        "actual_voltage": "Actual Voltage",
        "voltage_unit": "V",
        "slew_rate_enable": "Slew Rate Enable",
        "slew_rate": "Slew Rate",
        "slew_rate_unit": "V/s",
        "pc_arc_factor_unit": "V/V",
        "pressure_compensation": "Pressure Compensation",
        "enabled_label": "Enabled",
        "air_pressure": "Air Pressure",
        "air_pressure_unit": "hPa",
        "pressure_comp_factor": "Factor",
        "pressure_comp_factor_unit": "V/hPa",
        "compensation_voltage": "Compensation Voltage",
        "none": "None",
        "fine_in_1": "Fine In 1",
        "fine_in_2": "Fine In 2",
        "fast_in_3": "Fast In 3",
        "fast_in_4": "Fast In 4",
        "enabled_state": "Enabled",
        "disabled_state": "Disabled",
        "arc_factor_unit": "mA/V",
        "feedforward_factor_unit": "mA/K or mA/V",
        "device_overview": "Device Overview",
    },
}


PARAMETER_LABELS = {
    "system_label": {"zh": "系统标签", "en": "System Label"},
    "serial_number": {"zh": "设备序列号", "en": "Serial Number"},
    "fw_ver": {"zh": "固件版本", "en": "Firmware Version"},
    "system_type": {"zh": "系统类型", "en": "System Type"},
    "system_model": {"zh": "系统型号", "en": "System Model"},
    "uptime_txt": {"zh": "运行时间", "en": "Uptime"},
    "emission": {"zh": "系统发射", "en": "System Emission"},
    "interlock_open": {"zh": "联锁打开", "en": "Interlock Open"},
    "cc_enabled": {"zh": "CC 已使能", "en": "CC Enabled"},
    "cc_emission": {"zh": "CC 发射状态", "en": "CC Emission"},
    "current_set": {"zh": "设定电流", "en": "Current Set"},
    "current_act": {"zh": "实际电流", "en": "Current Actual"},
    "current_clip": {"zh": "最大电流限制", "en": "Current Clip"},
    "current_clip_tuning": {"zh": "Tuning Clip 电流上限", "en": "Tuning Clip Current Max"},
    "current_clip_limit": {"zh": "硬件电流上限", "en": "Hardware Current Limit"},
    "effective_current_max": {"zh": "当前可写入最大电流", "en": "Current Writable Max"},
    "use_current_clip_tuning": {"zh": "Use Tuning Clip", "en": "Use Tuning Clip"},
    "cc_status_txt": {"zh": "CC 状态文本", "en": "CC Status Text"},
    "latest_message": {"zh": "最新系统消息", "en": "Latest System Message"},
    "feedforward_enabled": {"zh": "前馈控制已启用", "en": "Feed Forward Enabled"},
    "feedforward_factor": {"zh": "前馈系数", "en": "Feed Forward Factor"},
    "arc_enabled": {"zh": "ARC 已启用", "en": "ARC Enabled"},
    "arc_signal": {"zh": "ARC 信号输入", "en": "ARC Signal Input"},
    "arc_factor": {"zh": "ARC 系数", "en": "ARC Factor"},
    "tc_enabled": {"zh": "TC 已启用", "en": "TC Enabled"},
    "temp_set": {"zh": "设定温度", "en": "Set Temperature"},
    "temp_act": {"zh": "实际温度", "en": "Actual Temperature"},
    "tc_arc_enabled": {"zh": "TC ARC 已启用", "en": "TC ARC Enabled"},
    "tc_arc_signal": {"zh": "TC ARC 信号输入", "en": "TC ARC Signal Input"},
    "tc_arc_factor": {"zh": "TC ARC 系数", "en": "TC ARC Factor"},
    "pc_enabled": {"zh": "PC 已启用", "en": "PC Enabled"},
    "pc_voltage_set": {"zh": "设定电压", "en": "Set Voltage"},
    "pc_voltage_act": {"zh": "实际电压", "en": "Actual Voltage"},
    "pc_slew_rate_enabled": {"zh": "PC 斜率限制已启用", "en": "PC Slew Rate Enabled"},
    "pc_slew_rate": {"zh": "PC 斜率限制", "en": "PC Slew Rate"},
    "pc_arc_enabled": {"zh": "PC ARC 已启用", "en": "PC ARC Enabled"},
    "pc_arc_signal": {"zh": "PC ARC 信号输入", "en": "PC ARC Signal Input"},
    "pc_arc_factor": {"zh": "PC ARC 系数", "en": "PC ARC Factor"},
    "pressure_comp_enabled": {"zh": "气压补偿已启用", "en": "Pressure Compensation Enabled"},
    "pressure_comp_air_pressure": {"zh": "气压", "en": "Air Pressure"},
    "pressure_comp_factor": {"zh": "补偿系数", "en": "Pressure Compensation Factor"},
    "pressure_comp_voltage": {"zh": "补偿电压", "en": "Compensation Voltage"},
}


ARC_SIGNAL_OPTIONS = [
    ("none", -3),
    ("fine_in_1", 0),
    ("fine_in_2", 1),
    ("fast_in_3", 2),
    ("fast_in_4", 4),
]
