from __future__ import annotations


AUTO_LOCK2_STRATEGY_OPTIONS = (
    ("auto_lock2_strategy_hybrid", "hybrid"),
    ("auto_lock2_strategy_transmission", "transmission_primary"),
    ("auto_lock2_strategy_error", "error_primary"),
)


TEXT = {
    "zh": {
        "window_title": "TOPTICA DLC pro 控制台",
        "language": "语言",
        "ui_scale": "界面缩放",
        "ui_scale_auto": "自动",
        "connection": "连接",
        "mode": "连接方式",
        "network": "网络",
        "serial": "串口",
        "host": "主机/IP/系统标签",
        "serial_port": "串口设备",
        "select_serial_port": "选择串口设备",
        "baudrate": "波特率",
        "timeout": "超时 (s)",
        "connect": "连接",
        "disconnect": "断开",
        "refresh": "刷新参数",
        "connected": "已连接",
        "disconnected": "未连接",
        "busy": "处理中...",
        "device_parameters": "当前设备参数",
        "parameter": "参数",
        "value": "当前值",
        "workspace": "功能区",
        "laser": "激光",
        "falc": "FALC",
        "scan_lock": "Scan&Lock",
        "relock": "Relock",
        "stabilization": "Stabilization",
        "stabilization_power_group": "Power Stabilization",
        "stabilization_detection": "Stabilization Detection",
        "stabilization_status_hint": "Built from verified SDK nodes: `laser1.power_stabilization` and `laser1.pd_ext`.",
        "stabilization_unavailable": "This device does not currently expose Power Stabilization nodes. Live controls will appear after a supported system is connected.",
        "stabilization_input_signal": "Input Signal",
        "stabilization_external_physical_channel": "External Power Physical Channel",
        "stabilization_photo_diode_value": "Photo Diode Value",
        "stabilization_cal_factor": "External Power Calibration Factor",
        "stabilization_cal_offset": "External Power Calibration Offset",
        "stabilization_set_level": "Set Level",
        "stabilization_actual_level": "Actual Level",
        "stabilization_output_signal": "Output Signal",
        "stabilization_gain": "Gain",
        "stabilization_hold_output_on_unlock": "Hold Output Signal on Unlock",
        "stabilization_level": "Level",
        "stabilization_input_channel_raw": "Input Channel",
        "stabilization_output_channel_raw": "Output Channel",
        "stabilization_input_signal_unverified": "The screenshot labels are used as UI reference, but the full official enum mapping for `power-stabilization:input-channel` is not confirmed in the SDK docs yet, so the current build safely shows device readback values only.",
        "stabilization_power_group": "Power Stabilization",
        "stabilization_detection": "Stabilization Detection",
        "stabilization_status_hint": "基于已验证的 SDK 节点开发：`laser1.power_stabilization`、`laser1.pd_ext`。",
        "stabilization_unavailable": "当前设备未暴露 Power Stabilization 节点；连接支持该功能的系统后这里会显示实时参数。",
        "stabilization_input_signal": "Input Signal",
        "stabilization_external_physical_channel": "External Power Physical Channel",
        "stabilization_photo_diode_value": "Photo Diode Value",
        "stabilization_cal_factor": "External Power Calibration Factor",
        "stabilization_cal_offset": "External Power Calibration Offset",
        "stabilization_set_level": "Set Level",
        "stabilization_actual_level": "Actual Level",
        "stabilization_output_signal": "Output Signal",
        "stabilization_gain": "Gain",
        "stabilization_hold_output_on_unlock": "Hold Output Signal on Unlock",
        "stabilization_level": "Level",
        "stabilization_input_channel_raw": "Input Channel",
        "stabilization_output_channel_raw": "Output Channel",
        "stabilization_input_signal_unverified": "截图中的通道名称已作为界面参考，但 `power-stabilization:input-channel` 的完整枚举值尚未在官方 SDK 文档中确认，因此当前仅安全显示设备回读值。",
        "lock_detection": "锁定检测",
        "relock_status_hint": "根据 SDK 与 Manual.md 已验证的 ReLock 参数进行配置。",
        "input_signal": "输入信号",
        "level_high": "高电平",
        "level_low": "低电平",
        "hysteresis": "回滞",
        "delay": "延时",
        "out_of_lock_action": "失锁动作",
        "enable_reset": "启用 PID1/2 复位",
        "relock_amplitude": "ReLock 幅度",
        "relock_frequency": "ReLock 频率",
        "relock_output_channel": "输出通道",
        "relock_window_rule_warning": "根据 Manual.md，Level High 必须大于或等于 Level Low + 2 x Hysteresis。",
        "placeholder_title": "预留页面",
        "placeholder_body": "这里预留给后续功能扩展。",
        "laser_page_title": "CC - 电流控制",
        "laser_page_subtitle": "激光控制",
        "current_control": "电流读取与控制",
        "current_set": "设定电流 (mA)",
        "current_act": "实际电流 (mA)",
        "current_clip": "最大电流限制 (mA)",
        "current_clip_tuning": "调谐限幅电流上限 (mA)",
        "current_clip_limit": "硬件电流上限 (mA)",
        "effective_current_max": "当前可写入最大电流 (mA)",
        "cc_status": "电流控制状态",
        "step_precision": "调节步进",
        "precision_target": "当前调节",
        "step_100": "100",
        "step_10": "10",
        "step_1_int": "1",
        "step_1": "0.1",
        "step_2": "0.01",
        "step_3": "0.001",
        "step_4": "0.0001",
        "step_5": "0.00001",
        "step_6": "0.000001",
        "auto_apply_hint": "修改设定电流后自动写入设备",
        "confirm_title": "确认快速调节",
        "confirm_apply_current": "本次将把设定电流从 {current:.5f} mA 调到 {value:.5f} mA，变化较大，确认继续吗？",
        "confirm_large_change_title": "确认参数写入",
        "confirm_large_change_body": "准备将 {label} 从 {current} 改为 {value}，确认继续吗？",
        "exit_confirm_title": "确认退出",
        "exit_confirm_body": "确定要关闭程序吗？",
        "connection_lost_title": "连接已断开",
        "safety_title": "安全提示",
        "safety_text": (
            "依据 Manual.md：带 MOTOR pro 的激光头在做 motor scan 前，"
            "应启用调谐限幅，避免损伤激光二极管。"
        ),
        "serial_ports": "可用串口",
        "network_adapters": "本机网卡",
        "not_available": "未安装或不可用",
        "latest_message": "最新系统消息",
        "emission": "系统发射",
        "interlock": "联锁打开",
        "cc_enabled": "CC 已启用",
        "cc_emission": "CC 发射状态",
        "enable": "启用",
        "disable": "禁用",
        "maximum_current": "最大电流",
        "feedforward": "前馈控制",
        "feedforward_factor": "前馈系数",
        "arc": "模拟远程控制",
        "arc_signal_input": "ARC 信号输入",
        "arc_factor": "ARC 系数",
        "temperature_control": "TC - 温度控制",
        "set_temperature": "设定温度",
        "actual_temperature": "实际温度",
        "temperature_unit": "°C",
        "tc_arc_factor_unit": "K/V",
        "piezo_control": "PC - 压电控制",
        "scan_control": "SC - 扫描控制",
        "lock_settings": "Lock Settings",
        "lock_enable": "启用",
        "lock_hold": "保持",
        "lock_input_signal": "锁定输入信号",
        "lock_error_input_signal": "误差信号输入",
        "lock_type": "锁定类型",
        "pid_selection": "PID 选择",
        "lock_falc_selection": "FALC 关联",
        "lock_without_lockpoint": "无锁点锁定",
        "lock_status": "锁定状态",
        "lock_candidate_filter": "候选锁点过滤",
        "lock_candidate_top": "峰值候选点",
        "lock_candidate_bottom": "谷值候选点",
        "lock_candidate_positive_edge": "正边沿候选点",
        "lock_candidate_negative_edge": "负边沿候选点",
        "lock_candidate_edge_level": "边沿电平",
        "lock_candidate_peak_noise_tolerance": "峰值/噪声容差",
        "lock_candidate_edge_min_distance": "最小边沿间距",
        "lock_candidate_top_of_fringe_low_pass": "峰值模式低通",
        "pid1_section": "PID 1",
        "pid2_section": "PID 2",
        "pid_gain": "Gain",
        "pid_p": "P",
        "pid_i": "I",
        "pid_d": "D",
        "pid_output_channel": "Output Channel",
        "pid_sign_positive": "Sign Positive",
        "pid_use_i_cutoff": "Use I cut-off",
        "pid_i_cutoff": "I cut-off",
        "pid_use_limit": "Use Limit",
        "pid_limit": "Limit",
        "pid_enable": "Enable PID",
        "set_voltage": "设定电压",
        "actual_voltage": "实际电压",
        "voltage_unit": "V",
        "falc_input": "输入",
        "falc_input_gain": "输入增益",
        "falc_offset": "偏置",
        "falc_link": "Click & Lock 链路",
        "falc_path_selection": "FALC 路径",
        "falc_hold_state": "总保持状态",
        "falc_mon_config": "监视输出",
        "falc_main": "主回路",
        "falc_main_gain": "主回路增益",
        "falc_main_lock_state": "Main 锁定状态",
        "falc_main_use_external_input": "使用外部增益输入",
        "falc_gain_unit": "dB",
        "falc_unlim": "Unlim",
        "falc_unlim_input_offset": "输入偏置",
        "falc_unlim_output_range": "输出范围",
        "falc_unlim_slew_rate": "斜率等级",
        "falc_unlim_gain": "增益",
        "falc_unlim_hold": "保持",
        "falc_unlim_lock_state": "Unlim 锁定状态",
        "falc_unlim_regulating_state": "Unlim 调节中",
        "falc_unlim_sign_positive": "正号输出",
        "falc_unlim_gain_unit": "V/V/s",
        "falc_unlim_input_offset_unit": "mV",
        "falc_unavailable": "当前未检测到 FALC 1 模块，连接对应模块后这里会显示实时参数。",
        "scan_amplitude": "扫描幅度",
        "scan_offset": "扫描偏置",
        "scan_output": "扫描输出",
        "scan_frequency": "扫描频率",
        "scan_shape": "扫描波形",
        "scan_amplitude_unit": "V pp",
        "scan_shape_sine": "正弦",
        "scan_shape_triangle": "三角波",
        "scan_output_cc_current": "CC 电流",
        "scan_output_pc_voltage": "PC 电压",
        "scan_output_out_a": "输出 A",
        "scan_output_out_b": "输出 B",
        "scan_output_eom_voltage_slow": "EOM 慢电压",
        "scan_output_tc_set_temperature": "TC 设定温度",
        "scan_output_opo_slow_pzt_voltage": "OPO 慢 PZT 电压",
        "scan_output_opo_fast_pzt_voltage": "OPO 快 PZT 电压",
        "lock_input_fine_in_1": "Fine In 1",
        "lock_input_fine_in_2": "Fine In 2",
        "lock_input_fast_in_3": "Fast In 3",
        "lock_input_fast_in_4": "Fast In 4",
        "lock_input_pdh_in_1": "PDH In 1",
        "lock_input_pdh_in_2": "PDH In 2",
        "lock_error_pdh_1": "PDH Error 1",
        "lock_error_pdh_2": "PDH Error 2",
        "lock_type_top_of_fringe": "Top of Fringe",
        "lock_type_side_of_fringe": "Side of Fringe",
        "lock_type_top_of_fringe_pdh": "Top of Fringe PDH",
        "falc_1_option": "FALC 1",
        "falc_2_option": "FALC 2",
        "falc_3_option": "FALC 3",
        "falc_4_option": "FALC 4",
        "falc_path_none": "None",
        "falc_path_unlim": "Unlim",
        "falc_path_main": "Main",
        "falc_path_unlim_main": "Unlim + Main",
        "falc_mon_error": "Error",
        "falc_mon_main": "Main",
        "falc_mon_main_rms": "Main RMS",
        "pid_none": "None",
        "pid_1": "PID 1",
        "pid_2": "PID 2",
        "pid_1_2": "PID 1+2",
        "pid_output_pc_voltage": "PC 电压",
        "pid_output_cc_current": "CC 电流",
        "pid_output_out_a": "输出 A",
        "pid_output_out_b": "输出 B",
        "pid_output_eom_voltage_slow": "EOM 慢电压",
        "pid_gain_unit_none": "",
        "pid_p_unit_current": "mA/V",
        "pid_i_unit_current": "mA/V/ms",
        "pid_d_unit_current": "mA/V*us",
        "pid_limit_unit_current": "mA",
        "pid_p_unit_voltage": "V/V",
        "pid_i_unit_voltage": "V/V/ms",
        "pid_d_unit_voltage": "V/V*us",
        "pid_limit_unit_voltage": "V",
        "slew_rate_enable": "斜率限制启用",
        "slew_rate": "斜率限制",
        "slew_rate_unit": "V/s",
        "pc_arc_factor_unit": "V/V",
        "pressure_compensation": "气压补偿",
        "enabled_label": "启用",
        "air_pressure": "气压",
        "air_pressure_unit": "hPa",
        "pressure_comp_factor": "补偿系数",
        "pressure_comp_factor_unit": "V/hPa",
        "compensation_voltage": "补偿电压",
        "none": "无",
        "fine_in_1": "精细输入 1",
        "fine_in_2": "精细输入 2",
        "fast_in_3": "快速输入 3",
        "fast_in_4": "快速输入 4",
        "enabled_state": "已启用",
        "disabled_state": "已禁用",
        "locked_state": "已锁定",
        "unlocked_state": "未锁定",
        "active_state": "进行中",
        "inactive_state": "未进行",
        "arc_factor_unit": "mA/V",
        "feedforward_factor_unit": "mA/K 或 mA/V",
        "device_overview": "设备概览",
    },
    "en": {
        "window_title": "TOPTICA DLC pro Console",
        "language": "Language",
        "ui_scale": "UI Scale",
        "ui_scale_auto": "Auto",
        "connection": "Connection",
        "mode": "Mode",
        "network": "Network",
        "serial": "Serial",
        "host": "Host/IP/System Label",
        "serial_port": "Serial Port",
        "select_serial_port": "Select Serial Port",
        "baudrate": "Baudrate",
        "timeout": "Timeout (s)",
        "connect": "Connect",
        "disconnect": "Disconnect",
        "refresh": "Refresh",
        "connected": "Connected",
        "disconnected": "Disconnected",
        "busy": "Working...",
        "device_parameters": "Current Device Parameters",
        "parameter": "Parameter",
        "value": "Value",
        "workspace": "Workspace",
        "laser": "Laser",
        "falc": "FALC",
        "scan_lock": "Scan&Lock",
        "relock": "Relock",
        "stabilization": "Stabilization",
        "lock_detection": "Lock Detection",
        "relock_status_hint": "Configure ReLock using parameters verified against the SDK and Manual.md.",
        "input_signal": "Input Signal",
        "level_high": "Level High",
        "level_low": "Level Low",
        "hysteresis": "Hysteresis",
        "delay": "Delay",
        "out_of_lock_action": "Out of Lock Action",
        "enable_reset": "Enable PID1/2 Reset",
        "relock_amplitude": "Amplitude",
        "relock_frequency": "Frequency",
        "relock_output_channel": "Output Channel",
        "relock_window_rule_warning": "Per Manual.md, Level High must be greater than or equal to Level Low + 2 x Hysteresis.",
        "placeholder_title": "Reserved Page",
        "placeholder_body": "This page is reserved for future expansion.",
        "laser_page_title": "CC - Current Control",
        "laser_page_subtitle": "Laser Control",
        "current_control": "Current Readback and Control",
        "current_set": "Set Current Iset (mA)",
        "current_act": "Actual Current Iact (mA)",
        "current_clip": "Current Clip (mA)",
        "current_clip_tuning": "Tuning Clip Current Max (mA)",
        "current_clip_limit": "Hardware Current Limit (mA)",
        "effective_current_max": "Current Writable Max (mA)",
        "cc_status": "Current Controller Status",
        "step_precision": "Adjustment Step",
        "precision_target": "Current Target",
        "step_100": "100",
        "step_10": "10",
        "step_1_int": "1",
        "step_1": "0.1",
        "step_2": "0.01",
        "step_3": "0.001",
        "step_4": "0.0001",
        "step_5": "0.00001",
        "step_6": "0.000001",
        "auto_apply_hint": "Set current is written automatically after adjustment",
        "confirm_title": "Confirm Fast Adjustment",
        "confirm_apply_current": "Change set current from {current:.5f} mA to {value:.5f} mA? This is a large adjustment.",
        "confirm_large_change_title": "Confirm Parameter Write",
        "confirm_large_change_body": "Change {label} from {current} to {value}?",
        "exit_confirm_title": "Confirm Exit",
        "exit_confirm_body": "Close the application?",
        "connection_lost_title": "Connection Lost",
        "safety_title": "Safety Note",
        "safety_text": (
            "Per Manual.md: for laser heads with MOTOR pro, enable Use Tuning Clip "
            "before a motor scan to avoid laser diode damage."
        ),
        "serial_ports": "Available Serial Ports",
        "network_adapters": "Local Network Adapters",
        "not_available": "Not installed or unavailable",
        "latest_message": "Latest System Message",
        "emission": "System Emission",
        "interlock": "Interlock Open",
        "cc_enabled": "CC Enabled",
        "cc_emission": "CC Emission",
        "enable": "Enable",
        "disable": "Disable",
        "maximum_current": "Maximum Current",
        "feedforward": "Feed Forward",
        "feedforward_factor": "Feed Forward Factor",
        "arc": "Analog Remote Control",
        "arc_signal_input": "ARC Signal Input",
        "arc_factor": "ARC Factor",
        "temperature_control": "TC - Temperature Control",
        "set_temperature": "Set Temperature",
        "actual_temperature": "Actual Temperature",
        "temperature_unit": "°C",
        "tc_arc_factor_unit": "K/V",
        "piezo_control": "PC - Piezo Control",
        "scan_control": "SC - Scan Control",
        "lock_settings": "Lock Settings",
        "lock_enable": "Enable",
        "lock_hold": "Hold",
        "lock_input_signal": "Lock Input Signal",
        "lock_error_input_signal": "Error Input Signal",
        "lock_type": "Lock Type",
        "pid_selection": "PID Selection",
        "lock_falc_selection": "FALC Selection",
        "lock_without_lockpoint": "Lock Without Lockpoint",
        "lock_status": "Lock State",
        "lock_candidate_filter": "Lock Candidate Filter",
        "lock_candidate_top": "Peak Candidates",
        "lock_candidate_bottom": "Trough Candidates",
        "lock_candidate_positive_edge": "Positive Edge Candidates",
        "lock_candidate_negative_edge": "Negative Edge Candidates",
        "lock_candidate_edge_level": "Edge Level",
        "lock_candidate_peak_noise_tolerance": "Peak/Noise Tolerance",
        "lock_candidate_edge_min_distance": "Edge Min Distance",
        "lock_candidate_top_of_fringe_low_pass": "Top-of-Fringe Low Pass",
        "pid1_section": "PID 1",
        "pid2_section": "PID 2",
        "pid_gain": "Gain",
        "pid_p": "P",
        "pid_i": "I",
        "pid_d": "D",
        "pid_output_channel": "Output Channel",
        "pid_sign_positive": "Sign Positive",
        "pid_use_i_cutoff": "Use I cut-off",
        "pid_i_cutoff": "I cut-off",
        "pid_use_limit": "Use Limit",
        "pid_limit": "Limit",
        "pid_enable": "Enable PID",
        "set_voltage": "Set Voltage",
        "actual_voltage": "Actual Voltage",
        "voltage_unit": "V",
        "falc_input": "Input",
        "falc_input_gain": "Input Gain",
        "falc_offset": "Offset",
        "falc_link": "Click & Lock Link",
        "falc_path_selection": "FALC Path",
        "falc_hold_state": "Global Hold State",
        "falc_mon_config": "Monitor Output",
        "falc_main": "Main",
        "falc_main_gain": "Main Gain",
        "falc_main_lock_state": "Main Lock State",
        "falc_main_use_external_input": "Use External Gain Input",
        "falc_gain_unit": "dB",
        "falc_unlim": "Unlim",
        "falc_unlim_input_offset": "Input Offset",
        "falc_unlim_output_range": "Output Range",
        "falc_unlim_slew_rate": "Slew Rate",
        "falc_unlim_gain": "Gain",
        "falc_unlim_hold": "Hold",
        "falc_unlim_lock_state": "Unlim Lock State",
        "falc_unlim_regulating_state": "Unlim Regulating",
        "falc_unlim_sign_positive": "Sign Positive",
        "falc_unlim_gain_unit": "V/V/s",
        "falc_unlim_input_offset_unit": "mV",
        "falc_unavailable": "FALC 1 is not currently available. Live controls will appear after the module is detected.",
        "scan_amplitude": "Scan Amplitude",
        "scan_offset": "Scan Offset",
        "scan_output": "Scan Output",
        "scan_frequency": "Scan Frequency",
        "scan_shape": "Scan Shape",
        "scan_amplitude_unit": "V pp",
        "scan_shape_sine": "Sine",
        "scan_shape_triangle": "Triangle",
        "scan_output_cc_current": "CC Current",
        "scan_output_pc_voltage": "PC Voltage",
        "scan_output_out_a": "Out A",
        "scan_output_out_b": "Out B",
        "scan_output_eom_voltage_slow": "EOM Voltage Slow",
        "scan_output_tc_set_temperature": "TC Set Temperature",
        "scan_output_opo_slow_pzt_voltage": "OPO Slow PZT Voltage",
        "scan_output_opo_fast_pzt_voltage": "OPO Fast PZT Voltage",
        "lock_input_fine_in_1": "Fine In 1",
        "lock_input_fine_in_2": "Fine In 2",
        "lock_input_fast_in_3": "Fast In 3",
        "lock_input_fast_in_4": "Fast In 4",
        "lock_input_pdh_in_1": "PDH In 1",
        "lock_input_pdh_in_2": "PDH In 2",
        "lock_error_pdh_1": "PDH Error 1",
        "lock_error_pdh_2": "PDH Error 2",
        "lock_type_top_of_fringe": "Top of Fringe",
        "lock_type_side_of_fringe": "Side of Fringe",
        "lock_type_top_of_fringe_pdh": "Top of Fringe PDH",
        "falc_1_option": "FALC 1",
        "falc_2_option": "FALC 2",
        "falc_3_option": "FALC 3",
        "falc_4_option": "FALC 4",
        "falc_path_none": "None",
        "falc_path_unlim": "Unlim",
        "falc_path_main": "Main",
        "falc_path_unlim_main": "Unlim + Main",
        "falc_mon_error": "Error",
        "falc_mon_main": "Main",
        "falc_mon_main_rms": "Main RMS",
        "pid_none": "None",
        "pid_1": "PID 1",
        "pid_2": "PID 2",
        "pid_1_2": "PID 1+2",
        "pid_output_pc_voltage": "PC Voltage",
        "pid_output_cc_current": "CC Current",
        "pid_output_out_a": "Out A",
        "pid_output_out_b": "Out B",
        "pid_output_eom_voltage_slow": "EOM Voltage Slow",
        "pid_gain_unit_none": "",
        "pid_p_unit_current": "mA/V",
        "pid_i_unit_current": "mA/V/ms",
        "pid_d_unit_current": "mA/V*us",
        "pid_limit_unit_current": "mA",
        "pid_p_unit_voltage": "V/V",
        "pid_i_unit_voltage": "V/V/ms",
        "pid_d_unit_voltage": "V/V*us",
        "pid_limit_unit_voltage": "V",
        "slew_rate_enable": "Slew Rate Enable",
        "slew_rate": "Slew Rate",
        "slew_rate_unit": "V/s",
        "pc_arc_factor_unit": "V/V",
        "pressure_compensation": "Pressure Compensation",
        "enabled_label": "Enabled",
        "air_pressure": "Air Pressure",
        "air_pressure_unit": "hPa",
        "pressure_comp_factor": "Factor",
        "pressure_comp_factor_unit": "V/hPa",
        "compensation_voltage": "Compensation Voltage",
        "none": "None",
        "fine_in_1": "Fine In 1",
        "fine_in_2": "Fine In 2",
        "fast_in_3": "Fast In 3",
        "fast_in_4": "Fast In 4",
        "enabled_state": "Enabled",
        "disabled_state": "Disabled",
        "locked_state": "Locked",
        "unlocked_state": "Unlocked",
        "active_state": "Active",
        "inactive_state": "Inactive",
        "arc_factor_unit": "mA/V",
        "feedforward_factor_unit": "mA/K or mA/V",
        "device_overview": "Device Overview",
    },
}


PARAMETER_LABELS = {
    "system_label": {"zh": "系统标签", "en": "System Label"},
    "serial_number": {"zh": "设备序列号", "en": "Serial Number"},
    "fw_ver": {"zh": "固件版本", "en": "Firmware Version"},
    "system_type": {"zh": "系统类型", "en": "System Type"},
    "system_model": {"zh": "系统型号", "en": "System Model"},
    "uptime_txt": {"zh": "运行时间", "en": "Uptime"},
    "emission": {"zh": "系统发射", "en": "System Emission"},
    "interlock_open": {"zh": "联锁打开", "en": "Interlock Open"},
    "cc_enabled": {"zh": "CC 已使能", "en": "CC Enabled"},
    "cc_emission": {"zh": "CC 发射状态", "en": "CC Emission"},
    "current_set": {"zh": "设定电流", "en": "Current Set"},
    "current_act": {"zh": "实际电流", "en": "Current Actual"},
    "current_clip": {"zh": "最大电流限制", "en": "Current Clip"},
    "current_clip_tuning": {"zh": "Tuning Clip 电流上限", "en": "Tuning Clip Current Max"},
    "current_clip_limit": {"zh": "硬件电流上限", "en": "Hardware Current Limit"},
    "effective_current_max": {"zh": "当前可写入最大电流", "en": "Current Writable Max"},
    "use_current_clip_tuning": {"zh": "Use Tuning Clip", "en": "Use Tuning Clip"},
    "cc_status_txt": {"zh": "CC 状态文本", "en": "CC Status Text"},
    "latest_message": {"zh": "最新系统消息", "en": "Latest System Message"},
    "feedforward_enabled": {"zh": "前馈控制已启用", "en": "Feed Forward Enabled"},
    "feedforward_factor": {"zh": "前馈系数", "en": "Feed Forward Factor"},
    "arc_enabled": {"zh": "ARC 已启用", "en": "ARC Enabled"},
    "arc_signal": {"zh": "ARC 信号输入", "en": "ARC Signal Input"},
    "arc_factor": {"zh": "ARC 系数", "en": "ARC Factor"},
    "tc_enabled": {"zh": "TC 已启用", "en": "TC Enabled"},
    "temp_set": {"zh": "设定温度", "en": "Set Temperature"},
    "temp_act": {"zh": "实际温度", "en": "Actual Temperature"},
    "tc_arc_enabled": {"zh": "TC ARC 已启用", "en": "TC ARC Enabled"},
    "tc_arc_signal": {"zh": "TC ARC 信号输入", "en": "TC ARC Signal Input"},
    "tc_arc_factor": {"zh": "TC ARC 系数", "en": "TC ARC Factor"},
    "pc_enabled": {"zh": "PC 已启用", "en": "PC Enabled"},
    "pc_voltage_set": {"zh": "设定电压", "en": "Set Voltage"},
    "pc_voltage_act": {"zh": "实际电压", "en": "Actual Voltage"},
    "pc_slew_rate_enabled": {"zh": "PC 斜率限制已启用", "en": "PC Slew Rate Enabled"},
    "pc_slew_rate": {"zh": "PC 斜率限制", "en": "PC Slew Rate"},
    "pc_arc_enabled": {"zh": "PC ARC 已启用", "en": "PC ARC Enabled"},
    "pc_arc_signal": {"zh": "PC ARC 信号输入", "en": "PC ARC Signal Input"},
    "pc_arc_factor": {"zh": "PC ARC 系数", "en": "PC ARC Factor"},
    "sc_enabled": {"zh": "SC 已启用", "en": "SC Enabled"},
    "sc_amplitude": {"zh": "扫描幅度", "en": "Scan Amplitude"},
    "sc_offset": {"zh": "扫描偏置", "en": "Scan Offset"},
    "sc_output_channel": {"zh": "扫描输出", "en": "Scan Output"},
    "sc_frequency": {"zh": "扫描频率", "en": "Scan Frequency"},
    "sc_signal_type": {"zh": "扫描波形", "en": "Scan Shape"},
    "sc_unit": {"zh": "扫描单位", "en": "Scan Unit"},
    "lock_enabled": {"zh": "锁定已启用", "en": "Lock Enabled"},
    "lock_hold": {"zh": "锁定保持", "en": "Lock Hold"},
    "lock_input_channel": {"zh": "锁定输入信号", "en": "Lock Input Signal"},
    "lock_type": {"zh": "锁定类型", "en": "Lock Type"},
    "lock_pid_selection": {"zh": "锁定 PID 选择", "en": "Lock PID Selection"},
    "lock_without_lockpoint": {"zh": "无锁点锁定", "en": "Lock Without Lockpoint"},
    "pid1_enabled": {"zh": "PID 1 已启用", "en": "PID 1 Enabled"},
    "pid1_gain_all": {"zh": "PID 1 Gain", "en": "PID 1 Gain"},
    "pid1_gain_p": {"zh": "PID 1 P", "en": "PID 1 P"},
    "pid1_gain_i": {"zh": "PID 1 I", "en": "PID 1 I"},
    "pid1_gain_d": {"zh": "PID 1 D", "en": "PID 1 D"},
    "pid1_output_channel": {"zh": "PID 1 输出通道", "en": "PID 1 Output Channel"},
    "pid1_sign": {"zh": "PID 1 正号", "en": "PID 1 Sign Positive"},
    "pid1_i_cutoff_enabled": {"zh": "PID 1 I 截止已启用", "en": "PID 1 I Cut-off Enabled"},
    "pid1_i_cutoff": {"zh": "PID 1 I 截止频率", "en": "PID 1 I Cut-off"},
    "pid1_limit_enabled": {"zh": "PID 1 限幅已启用", "en": "PID 1 Limit Enabled"},
    "pid1_limit_max": {"zh": "PID 1 限幅", "en": "PID 1 Limit"},
    "pid2_enabled": {"zh": "PID 2 已启用", "en": "PID 2 Enabled"},
    "pid2_gain_all": {"zh": "PID 2 Gain", "en": "PID 2 Gain"},
    "pid2_gain_p": {"zh": "PID 2 P", "en": "PID 2 P"},
    "pid2_gain_i": {"zh": "PID 2 I", "en": "PID 2 I"},
    "pid2_gain_d": {"zh": "PID 2 D", "en": "PID 2 D"},
    "pid2_output_channel": {"zh": "PID 2 输出通道", "en": "PID 2 Output Channel"},
    "pid2_sign": {"zh": "PID 2 正号", "en": "PID 2 Sign Positive"},
    "pid2_limit_enabled": {"zh": "PID 2 限幅已启用", "en": "PID 2 Limit Enabled"},
    "pid2_limit_max": {"zh": "PID 2 限幅", "en": "PID 2 Limit"},
    "pressure_comp_enabled": {"zh": "气压补偿已启用", "en": "Pressure Compensation Enabled"},
    "pressure_comp_air_pressure": {"zh": "气压", "en": "Air Pressure"},
    "pressure_comp_factor": {"zh": "补偿系数", "en": "Pressure Compensation Factor"},
    "pressure_comp_voltage": {"zh": "补偿电压", "en": "Compensation Voltage"},
}


ARC_SIGNAL_OPTIONS = [
    ("none", -3),
    ("fine_in_1", 0),
    ("fine_in_2", 1),
    ("fast_in_3", 2),
    ("fast_in_4", 4),
]


SCAN_OUTPUT_OPTIONS = [
    ("scan_output_cc_current", 51),
    ("scan_output_pc_voltage", 50),
    ("scan_output_out_a", 20),
    ("scan_output_out_b", 21),
    ("scan_output_eom_voltage_slow", 58),
    ("scan_output_tc_set_temperature", 56),
    ("scan_output_opo_slow_pzt_voltage", 150),
    ("scan_output_opo_fast_pzt_voltage", 151),
]


SCAN_SHAPE_OPTIONS = [
    ("scan_shape_sine", 0),
    ("scan_shape_triangle", 1),
]


LOCK_INPUT_SIGNAL_OPTIONS = [
    ("lock_input_fine_in_1", 0),
    ("lock_input_fine_in_2", 1),
    ("lock_input_fast_in_3", 2),
    ("lock_input_fast_in_4", 4),
    ("lock_input_pdh_in_1", 41),
    ("lock_input_pdh_in_2", 43),
]


LOCK_ERROR_SIGNAL_OPTIONS = [
    ("lock_input_fine_in_1", 0),
    ("lock_input_fine_in_2", 1),
    ("lock_input_fast_in_3", 2),
    ("lock_input_fast_in_4", 4),
    ("lock_error_pdh_1", 40),
    ("lock_error_pdh_2", 42),
]


LOCK_TYPE_OPTIONS = [
    ("lock_type_top_of_fringe", 1),
    ("lock_type_side_of_fringe", 2),
    ("lock_type_top_of_fringe_pdh", 3),
]


LOCK_PID_SELECTION_OPTIONS = [
    ("pid_none", 0),
    ("pid_1", 1),
    ("pid_2", 2),
    ("pid_1_2", 3),
]


LOCK_FALC_SELECTION_OPTIONS = [
    ("none", 0),
    ("falc_1_option", 1),
    ("falc_2_option", 2),
    ("falc_3_option", 3),
    ("falc_4_option", 4),
]


FALC_PATH_SELECTION_OPTIONS = [
    ("falc_path_none", 0),
    ("falc_path_unlim", 1),
    ("falc_path_main", 2),
    ("falc_path_unlim_main", 3),
]


FALC_MON_CONFIG_OPTIONS = [
    ("falc_mon_error", 0),
    ("falc_mon_main", 1),
    ("falc_mon_main_rms", 2),
]


PID_OUTPUT_CHANNEL_OPTIONS = [
    ("pid_output_pc_voltage", 50),
    ("pid_output_cc_current", 51),
    ("pid_output_out_a", 20),
    ("pid_output_out_b", 21),
    ("pid_output_eom_voltage_slow", 58),
]


RELOCK_OUTPUT_CHANNEL_OPTIONS = [
    ("pid_output_pc_voltage", 50),
    ("pid_output_cc_current", 51),
    ("pid_output_out_a", 20),
    ("pid_output_out_b", 21),
]


STABILIZATION_PHYSICAL_CHANNEL_OPTIONS = [
    ("fine_in_1", 0),
    ("fine_in_2", 1),
    ("fast_in_3", 2),
    ("fast_in_4", 4),
]


STABILIZATION_OUTPUT_CHANNEL_OPTIONS = [
    ("pid_output_cc_current", 51),
]


AUTO_LOCK_STRATEGY_OPTIONS = [
    ("auto_lock_strategy_nearest_center", "nearest_center"),
    ("auto_lock_strategy_nearest_last", "nearest_last"),
    ("auto_lock_strategy_highest_y", "highest_y"),
    ("auto_lock_strategy_leftmost", "leftmost"),
    ("auto_lock_strategy_rightmost", "rightmost"),
]


AUTO_LOCK_SCOPE_SIGNAL_OPTIONS = [
    ("none", -3),
    ("fine_in_1", 0),
    ("fine_in_2", 1),
    ("fast_in_3", 2),
    ("fast_in_4", 4),
    ("auto_lock_scope_signal_lock_input", 100),
    ("auto_lock_scope_signal_lockin_output", 30),
    ("auto_lock_scope_signal_pid1_output", 31),
    ("auto_lock_scope_signal_pid2_output", 32),
    ("lock_input_pdh_in_1", 41),
    ("auto_lock_scope_signal_pdh_error_1", 40),
    ("lock_input_pdh_in_2", 43),
    ("auto_lock_scope_signal_pdh_error_2", 42),
    ("pid_output_cc_current", 51),
    ("pid_output_pc_voltage", 50),
    ("auto_lock_scope_signal_sc_output", 101),
]


AUTO_LOCK_SCOPE_UPDATE_RATE_OPTIONS = [1, 2, 3, 4, 5, 10]


TEXT["zh"].update(
    {
        "auto_lock": "自动锁频",
        "auto_lock_status_hint": "基于官方 SDK 的 lock.candidates / lock_state 与 Manual.md 的 Lock Without Lockpoint 流程：先找候选锁点，再把目标移到中心后使能锁定。",
        "auto_lock_config": "自动锁频参数",
        "auto_lock_config_overview_hint": "这个区域负责配置一键锁定流程本身。运行状态、实时波形、候选锁点表和日志不在这里保存，它们属于运行时信息。",
        "auto_lock_basic_section": "基础参数",
        "auto_lock_advanced_section": "高级参数",
        "auto_lock_quick_link": "一键锁定链路配置",
        "auto_lock_preset_group": "本地预设",
        "auto_lock_preset_scope_hint": "本地预设只保存当前“自动锁频参数”区域里的内容，不保存运行状态、实时波形、候选锁点表、日志和当前已选锁点。",
        "auto_lock_preset_scope_title": "本地预设说明",
        "auto_lock_preset_scope_button": "预设说明",
        "auto_lock_preset_scope_button_hint": "查看本地预设会保存和不会保存的内容。",
        "auto_lock_preset_select": "已保存预设",
        "auto_lock_preset_selected": "当前加载预设",
        "auto_lock_preset_selected_none": "未加载",
        "auto_lock_preset_name": "预设名称",
        "auto_lock_preset_new": "新增预设",
        "auto_lock_preset_new_hint": "清空当前预设选择，准备保存一套新的自动锁频参数。",
        "auto_lock_preset_default_name": "新预设",
        "auto_lock_preset_delete": "删除预设",
        "auto_lock_preset_delete_hint": "删除当前选中的本地预设。",
        "auto_lock_preset_load": "加载预设",
        "auto_lock_preset_load_hint": "把当前选中的本地预设真正加载到自动锁频参数区域。",
        "auto_lock_preset_save": "保存预设",
        "auto_lock_preset_details": "预设内容",
        "auto_lock_preset_details_empty": "当前还没有可显示的预设内容。先选择一个已保存预设，或先填写参数后保存。",
        "auto_lock_preset_scope_current_title": "当前界面参数快照（如果现在点保存，下面这些内容会写进预设）",
        "auto_lock_preset_scope_saved_header": "会保存到本地预设的内容：",
        "auto_lock_preset_scope_saved_item_links": "链路配置：Error Input、FALC 关联、FALC Path。",
        "auto_lock_preset_scope_saved_item_workflow": "流程参数：选点策略、预扫时长、缩扫比例、搜索/等待/超时/重找时间。",
        "auto_lock_preset_scope_saved_item_candidate": "候选点过滤：Top/Bottom、Positive/Negative Edge、Edge Level、Peak/Noise Tolerance、Edge Min Distance、Top-of-Fringe Low Pass。",
        "auto_lock_preset_scope_saved_item_runtime": "运行选项：自动使能 SC、锁上后持续监视。",
        "auto_lock_preset_scope_not_saved_header": "不会保存到本地预设的内容：",
        "auto_lock_preset_scope_not_saved_item_runtime_status": "运行状态栏里的实时阶段、锁状态、候选数量、Offset、目标点、跟踪点和状态说明。",
        "auto_lock_preset_scope_not_saved_item_scope": "实时波形窗口和当前波形显示内容。",
        "auto_lock_preset_scope_not_saved_item_candidates": "当前候选锁点表和候选排序结果。",
        "auto_lock_preset_scope_not_saved_item_target": "当前手动点选的软件目标锁点、设备已选锁点、当前锁住的点。",
        "auto_lock_preset_scope_not_saved_item_templates": "本轮自动锁频运行过程中动态生成的固定模板进度。",
        "auto_lock_preset_saved_values_header": "这套预设当前保存的具体值：",
        "auto_lock_runtime": "运行状态",
        "auto_lock_template_progress": "当前预设",
        "auto_lock_template_progress_value": "{current} / {total}",
        "auto_lock_candidates": "候选锁点",
        "auto_lock_log": "运行日志",
        "auto_lock_scope": "实时波形",
        "auto_lock_scope_window_title": "自动锁频波形",
        "auto_lock_scope_status_hint": "依据 SDK 的 `laser1.scope.data` 与 `lock.candidates` 叠加显示。手册说明锁点点选依赖 XY 模式和 scope engine。",
        "auto_lock_scope_channel1": "红色通道",
        "auto_lock_scope_channel2": "蓝色通道",
        "auto_lock_scope_update_rate": "刷新率",
        "auto_lock_scope_mode": "显示模式",
        "auto_lock_scope_switch_xy": "切到 XY",
        "auto_lock_scope_open_window": "打开波形窗口",
        "auto_lock_scope_refresh": "刷新波形",
        "auto_lock_scope_click_hint": "点击灰色候选点可把它设为软件目标锁点。",
        "auto_lock_scope_switching": "正在切换显示模式到 {mode}...",
        "auto_lock_scope_mode_xy": "XY",
        "auto_lock_scope_mode_time": "Time",
        "auto_lock_scope_mode_frequency": "Frequency",
        "auto_lock_scope_signal_lock_input": "Lock Input",
        "auto_lock_scope_signal_lockin_output": "Lock-In Output",
        "auto_lock_scope_signal_pid1_output": "PID 1 Output",
        "auto_lock_scope_signal_pid2_output": "PID 2 Output",
        "auto_lock_scope_signal_pdh_error_1": "PDH Error 1",
        "auto_lock_scope_signal_pdh_error_2": "PDH Error 2",
        "auto_lock_scope_signal_sc_output": "SC Output",
        "auto_lock_scope_empty": "当前还没有可绘制的波形数据。",
        "auto_lock_scope_error_prefix": "波形读取异常：",
        "auto_lock_scope_target_marker": "软件目标",
        "auto_lock_scope_selected_marker": "设备已选点",
        "auto_lock_scope_tracking_marker": "设备跟踪点",
        "auto_lock_scope_candidates_marker": "候选点",
        "auto_lock_scope_background_marker": "锁定前背景",
        "auto_lock_strategy": "选点策略",
        "auto_lock_strategy_nearest_center": "离当前中心最近",
        "auto_lock_strategy_nearest_last": "离上次锁点最近",
        "auto_lock_strategy_highest_y": "Y 值最高",
        "auto_lock_strategy_leftmost": "最左侧",
        "auto_lock_strategy_rightmost": "最右侧",
        "auto_lock_search_interval": "搜索间隔",
        "auto_lock_settle_delay": "居中等待",
        "auto_lock_lock_timeout": "上锁超时",
        "auto_lock_monitor_interval": "监视间隔",
        "auto_lock_reacquire_delay": "重找延时",
        "auto_lock_pre_scan_duration": "预扫时长",
        "auto_lock_pre_scan_shrink_percent": "缩扫比例",
        "auto_lock_pre_scan_usage_hint": "“预扫并缩扫”只做两步：先按当前 Scan Amplitude 扫描一段时间，再自动把 Scan Amplitude 缩小到设定比例。它不会自动找锁点，也不会自动开锁。",
        "auto_lock_runtime_hint": "下面两项是运行时开关，影响自动流程怎么继续，不属于锁点本身。",
        "auto_lock_auto_enable_scan": "扫描关闭时自动使能 SC",
        "auto_lock_watch_after_lock": "锁上后持续监视并自动重找",
        "auto_lock_pre_scan_start": "预扫并缩扫",
        "auto_lock_pre_scan_dialog_title": "预扫并缩扫说明",
        "auto_lock_pre_scan_dialog_body": "这一步会执行以下动作：\n\n1. 使用当前 Scan Amplitude 开始扫频。\n2. 保持扫频 {duration_ms} ms。\n3. 到时间后把 Scan Amplitude 自动缩小到当前值的 {shrink_percent}%。\n\n这一步不会自动找锁点，也不会自动开 Lock。\n\n确认后开始执行。",
        "auto_lock_start": "开始自动锁频",
        "auto_lock_stop": "停止自动锁频",
        "auto_lock_clear_log": "清空日志",
        "auto_lock_phase": "当前阶段",
        "auto_lock_lock_state": "锁状态",
        "auto_lock_lock_enabled": "Lock Enable",
        "auto_lock_candidate_count": "候选数量",
        "auto_lock_scan_offset": "当前 Offset",
        "auto_lock_target": "当前目标",
        "auto_lock_tracking": "跟踪位置",
        "auto_lock_message": "状态说明",
        "auto_lock_table_index": "#",
        "auto_lock_table_x": "X",
        "auto_lock_table_y": "Y",
        "auto_lock_phase_idle": "空闲",
        "auto_lock_phase_searching": "搜索候选锁点",
        "auto_lock_phase_centering": "移动到中心",
        "auto_lock_phase_settling": "等待扫描稳定",
        "auto_lock_phase_locking": "等待锁定",
        "auto_lock_phase_monitoring": "锁定后监视",
        "auto_lock_phase_reacquiring": "脱锁后重找",
        "auto_lock_phase_pre_scan": "预扫中",
        "auto_lock_phase_pre_scan_narrowing": "缩小扫描范围",
        "auto_lock_state_unknown": "原始状态 {value}",
        "auto_lock_state_selected": "Selected",
        "auto_lock_state_locked": "Locked",
        "auto_lock_value_none": "无",
        "auto_lock_value_waiting": "等待中",
        "auto_lock_window_stopped": "自动锁频已停止，当前不会再继续搜索或重锁。",
        "auto_lock_log_started": "启动自动锁频流程。",
        "auto_lock_log_stopped": "停止自动锁频流程。",
        "auto_lock_log_no_candidate": "当前没有候选锁点，继续等待下一轮扫描结果。",
        "auto_lock_log_scan_required": "扫描当前关闭且未启用“自动使能 SC”，无法继续自动找锁点。",
        "auto_lock_log_enable_scan": "扫描关闭，自动使能 SC 以继续寻找锁点。",
        "auto_lock_log_disable_lock": "检测到 Lock 已开启，先关闭当前锁定再重新找点。",
        "auto_lock_log_candidate_mode": "暂时关闭 Lock Without Lockpoint，用候选锁点模式寻找目标。",
        "auto_lock_log_select_target": "已选择候选锁点：X={x:.6f}，Y={y:.6f}。",
        "auto_lock_log_click_target": "已通过波形图选择目标锁点：X={x:.6f}，Y={y:.6f}。",
        "auto_lock_log_enable_center_lock": "切换到 Lock Without Lockpoint，并准备把目标移到中心。",
        "auto_lock_log_move_offset": "把 Scan Offset 移到目标锁点位置：{x:.6f}。",
        "auto_lock_log_enable_lock": "目标已居中，使能 Lock，等待 DLC pro 到达锁点后再接通 PID。",
        "auto_lock_log_lock_waiting": "尚未进入 Locked，当前原始状态为 {state}。",
        "auto_lock_log_lock_success": "已进入 Locked 状态，自动锁频完成。",
        "auto_lock_log_monitor_lost": "检测到已脱锁，准备重新搜索锁点。",
        "auto_lock_log_lock_timeout": "超过上锁超时仍未进入 Locked，准备重新搜索。",
        "auto_lock_log_retry_after_disable": "已清除当前锁定状态，稍后重新寻找锁点。",
        "auto_lock_log_scope_xy": "已将设备 Scope 切换到 XY 模式，便于候选锁点叠加显示。",
        "auto_lock_log_scope_variant": "已将设备 Scope 切换到 {mode} 模式。",
        "auto_lock_log_pre_scan_started": "启动预扫流程：保持当前扫描幅度 {amplitude:.6f}，持续 {duration_ms} ms 后自动缩扫。",
        "auto_lock_log_pre_scan_running": "预扫进行中：当前按扫描幅度 {amplitude:.6f} 运行，等待 {duration_ms} ms 后缩扫。",
        "auto_lock_log_pre_scan_narrowing": "开始缩扫：把 Scan Amplitude 从 {initial:.6f} 调整为 {target:.6f}。",
        "auto_lock_log_pre_scan_complete": "预扫流程完成：Scan Amplitude 已缩小到 {target:.6f}。",
        "auto_lock_log_pre_scan_stopped": "预扫流程已停止。",
        "auto_lock_log_template_start": "开始预设 {index}：宽扫幅度 {wide:.6f}，窄扫幅度 {narrow:.6f}。",
        "auto_lock_log_template_running": "预设 {index} 宽扫中：按扫描幅度 {amplitude:.6f} 运行 {duration_ms} ms 后进入窄扫。",
        "auto_lock_log_template_narrowing": "预设 {index} 开始窄扫：把 Scan Amplitude 从 {initial:.6f} 调整为 {target:.6f}。",
        "auto_lock_log_retry_template": "当前预设未锁住，从预设 {previous} 切换到预设 {current} 重试。",
        "auto_lock_log_no_candidate_advance": "当前预设连续未找到候选锁点，切换到下一套预设继续尝试。",
        "auto_lock_log_templates_exhausted": "所有固定预设都已尝试，自动锁频 V1 结束。",
        "auto_lock_preset_name_required": "请先输入一个预设名称再保存。",
        "auto_lock_preset_save_failed": "预设保存失败，请检查当前目录写入权限。",
        "auto_lock_preset_save_requires_existing": "当前还没有选中已有预设。请先点“新增预设”创建一个，再用“保存预设”更新它。",
        "auto_lock_preset_name_exists": "预设名称 {name} 已存在。请换一个名字，或先选中那个预设再修改。",
        "auto_lock_preset_created": "已新增自动锁频预设：{name}。",
        "auto_lock_preset_deleted": "已删除自动锁频预设：{name}。",
        "auto_lock_preset_saved": "已保存自动锁频预设：{name}。",
        "auto_lock_preset_loaded": "已加载自动锁频预设：{name}。",
        "auto_lock_preset_apply_busy": "已把预设 {name} 加载到界面，但设备当前正忙，链路参数稍后再手动应用。",
        "auto_lock_preset_delete_requires_selection": "请先选中一个要删除的预设。",
        "auto_lock_preset_delete_confirm_title": "删除预设",
        "auto_lock_preset_delete_confirm_body": "确认删除预设 {name} 吗？这个操作会从本地文件里移除它。",
        "auto_lock_preset_switch_confirm_title": "切换预设",
        "auto_lock_preset_switch_confirm_body": "确认切换到预设 {name} 吗？当前界面里的自动锁频参数会被这套预设覆盖。",
        "auto_lock_preset_create_success_title": "预设创建成功",
        "auto_lock_preset_delete_success_title": "预设删除成功",
        "auto_lock_preset_save_success_title": "预设保存成功",
        "auto_lock_preset_load_success_title": "预设切换成功",
        "auto_lock_warning_not_connected": "设备尚未连接，无法启动自动锁频。",
        "auto_lock_warning_busy": "当前还有设备任务在执行，请稍后再启动自动锁频。",
        "auto_lock_warning_scan_amplitude_zero": "当前 Scan Amplitude 为 0，无法执行预扫并缩扫。请先设置一个非零扫描幅度。",
    }
)


TEXT["en"].update(
    {
        "auto_lock": "Auto Lock",
        "auto_lock_status_hint": "Built from the official SDK lock.candidates / lock_state flow and the Manual.md Lock Without Lockpoint sequence: find candidates first, move the target to the center, then enable lock.",
        "auto_lock_config": "Auto Lock Settings",
        "auto_lock_config_overview_hint": "This area configures the one-click lock workflow itself. Runtime status, live scope traces, candidate tables, and logs are not part of the saved preset.",
        "auto_lock_basic_section": "Basic Settings",
        "auto_lock_advanced_section": "Advanced Settings",
        "auto_lock_quick_link": "One-Click Link Setup",
        "auto_lock_preset_group": "Local Presets",
        "auto_lock_preset_scope_hint": "A local preset only saves the values in the Auto Lock settings area. It does not save runtime status, live scope data, the candidate table, the log, or the currently selected lockpoint.",
        "auto_lock_preset_scope_title": "Local Preset Notes",
        "auto_lock_preset_scope_button": "Preset Notes",
        "auto_lock_preset_scope_button_hint": "Show what local presets save and do not save.",
        "auto_lock_preset_select": "Saved Preset",
        "auto_lock_preset_selected": "Loaded Preset",
        "auto_lock_preset_selected_none": "None loaded",
        "auto_lock_preset_name": "Preset Name",
        "auto_lock_preset_new": "New Preset",
        "auto_lock_preset_new_hint": "Clear the current preset selection and prepare to save a new Auto Lock setup.",
        "auto_lock_preset_default_name": "New Preset",
        "auto_lock_preset_delete": "Delete Preset",
        "auto_lock_preset_delete_hint": "Delete the currently selected local preset.",
        "auto_lock_preset_load": "Load Preset",
        "auto_lock_preset_load_hint": "Apply the selected local preset to the Auto Lock settings area.",
        "auto_lock_preset_save": "Save Preset",
        "auto_lock_preset_details": "Preset Details",
        "auto_lock_preset_details_empty": "No preset details are available yet. Select a saved preset, or configure values and save one first.",
        "auto_lock_preset_scope_current_title": "Current UI snapshot (if you save now, the items below will go into the preset)",
        "auto_lock_preset_scope_saved_header": "Saved into a local preset:",
        "auto_lock_preset_scope_saved_item_links": "Link setup: Error Input, FALC selection, and FALC path.",
        "auto_lock_preset_scope_saved_item_workflow": "Workflow settings: selection strategy, pre-scan duration, narrowed range, and search / settle / timeout / reacquire timings.",
        "auto_lock_preset_scope_saved_item_candidate": "Candidate filters: Top/Bottom, Positive/Negative Edge, Edge Level, Peak/Noise Tolerance, Edge Min Distance, and Top-of-Fringe Low Pass.",
        "auto_lock_preset_scope_saved_item_runtime": "Run options: automatically enable SC and keep watching after lock.",
        "auto_lock_preset_scope_not_saved_header": "Not saved into a local preset:",
        "auto_lock_preset_scope_not_saved_item_runtime_status": "Live values in the runtime bar such as phase, lock state, candidate count, offset, target, tracking, and status message.",
        "auto_lock_preset_scope_not_saved_item_scope": "The live scope window and its current traces.",
        "auto_lock_preset_scope_not_saved_item_candidates": "The current lockpoint candidate table and candidate ordering results.",
        "auto_lock_preset_scope_not_saved_item_target": "The current software-selected target, device-selected lockpoint, and currently locked point.",
        "auto_lock_preset_scope_not_saved_item_templates": "The dynamic fixed-template progress generated during the current Auto Lock run.",
        "auto_lock_preset_saved_values_header": "Concrete values currently stored in this preset:",
        "auto_lock_runtime": "Runtime Status",
        "auto_lock_template_progress": "Current Preset",
        "auto_lock_template_progress_value": "{current} / {total}",
        "auto_lock_candidates": "Lockpoint Candidates",
        "auto_lock_log": "Run Log",
        "auto_lock_scope": "Live Scope",
        "auto_lock_scope_window_title": "Auto Lock Scope",
        "auto_lock_scope_status_hint": "Overlay view built from the SDK `laser1.scope.data` and `lock.candidates`. The manual states that lockpoint picking depends on XY mode and a scope engine.",
        "auto_lock_scope_channel1": "Red Channel",
        "auto_lock_scope_channel2": "Blue Channel",
        "auto_lock_scope_update_rate": "Refresh Rate",
        "auto_lock_scope_mode": "Display Mode",
        "auto_lock_scope_switch_xy": "Switch to XY",
        "auto_lock_scope_open_window": "Open Scope Window",
        "auto_lock_scope_refresh": "Refresh Scope",
        "auto_lock_scope_click_hint": "Click a grey candidate marker to set the software target lockpoint.",
        "auto_lock_scope_switching": "Switching the display mode to {mode}...",
        "auto_lock_scope_mode_xy": "XY",
        "auto_lock_scope_mode_time": "Time",
        "auto_lock_scope_mode_frequency": "Frequency",
        "auto_lock_scope_signal_lock_input": "Lock Input",
        "auto_lock_scope_signal_lockin_output": "Lock-In Output",
        "auto_lock_scope_signal_pid1_output": "PID 1 Output",
        "auto_lock_scope_signal_pid2_output": "PID 2 Output",
        "auto_lock_scope_signal_pdh_error_1": "PDH Error 1",
        "auto_lock_scope_signal_pdh_error_2": "PDH Error 2",
        "auto_lock_scope_signal_sc_output": "SC Output",
        "auto_lock_scope_empty": "No drawable scope trace is available yet.",
        "auto_lock_scope_error_prefix": "Scope readback error: ",
        "auto_lock_scope_target_marker": "Software Target",
        "auto_lock_scope_selected_marker": "Device Selected",
        "auto_lock_scope_tracking_marker": "Device Tracking",
        "auto_lock_scope_candidates_marker": "Candidates",
        "auto_lock_scope_background_marker": "Pre-lock Background",
        "auto_lock_strategy": "Selection Strategy",
        "auto_lock_strategy_nearest_center": "Nearest to current center",
        "auto_lock_strategy_nearest_last": "Nearest to last lockpoint",
        "auto_lock_strategy_highest_y": "Highest Y value",
        "auto_lock_strategy_leftmost": "Leftmost",
        "auto_lock_strategy_rightmost": "Rightmost",
        "auto_lock_search_interval": "Search Interval",
        "auto_lock_settle_delay": "Center Settle Delay",
        "auto_lock_lock_timeout": "Lock Timeout",
        "auto_lock_monitor_interval": "Monitor Interval",
        "auto_lock_reacquire_delay": "Reacquire Delay",
        "auto_lock_pre_scan_duration": "Pre-scan Duration",
        "auto_lock_pre_scan_shrink_percent": "Narrowed Range",
        "auto_lock_pre_scan_usage_hint": "\"Pre-scan Then Narrow\" only does two steps: scan with the current Scan Amplitude for a while, then reduce Scan Amplitude to the configured percentage. It does not search candidates or enable Lock.",
        "auto_lock_runtime_hint": "These two options control how the workflow continues at runtime. They are behavior flags, not lockpoint data.",
        "auto_lock_auto_enable_scan": "Automatically enable SC when scan is off",
        "auto_lock_watch_after_lock": "Keep watching after lock and reacquire automatically",
        "auto_lock_pre_scan_start": "Pre-scan Then Narrow",
        "auto_lock_pre_scan_dialog_title": "Pre-scan Then Narrow",
        "auto_lock_pre_scan_dialog_body": "This step will do the following:\n\n1. Start scanning with the current Scan Amplitude.\n2. Keep scanning for {duration_ms} ms.\n3. After that, reduce Scan Amplitude to {shrink_percent}% of the current value.\n\nThis step does not search for candidates and does not enable Lock.\n\nContinue?",
        "auto_lock_start": "Start Auto Lock",
        "auto_lock_stop": "Stop Auto Lock",
        "auto_lock_clear_log": "Clear Log",
        "auto_lock_phase": "Phase",
        "auto_lock_lock_state": "Lock State",
        "auto_lock_lock_enabled": "Lock Enable",
        "auto_lock_candidate_count": "Candidate Count",
        "auto_lock_scan_offset": "Current Offset",
        "auto_lock_target": "Current Target",
        "auto_lock_tracking": "Tracking Position",
        "auto_lock_message": "Status Message",
        "auto_lock_table_index": "#",
        "auto_lock_table_x": "X",
        "auto_lock_table_y": "Y",
        "auto_lock_phase_idle": "Idle",
        "auto_lock_phase_searching": "Searching candidates",
        "auto_lock_phase_centering": "Centering target",
        "auto_lock_phase_settling": "Waiting for scan settle",
        "auto_lock_phase_locking": "Waiting for lock",
        "auto_lock_phase_monitoring": "Monitoring locked state",
        "auto_lock_phase_reacquiring": "Reacquiring after unlock",
        "auto_lock_phase_pre_scan": "Pre-scan running",
        "auto_lock_phase_pre_scan_narrowing": "Narrowing scan range",
        "auto_lock_state_unknown": "Raw state {value}",
        "auto_lock_state_selected": "Selected",
        "auto_lock_state_locked": "Locked",
        "auto_lock_value_none": "None",
        "auto_lock_value_waiting": "Waiting",
        "auto_lock_window_stopped": "Auto Lock has been stopped. No further search or relock will be performed.",
        "auto_lock_log_started": "Started the Auto Lock workflow.",
        "auto_lock_log_stopped": "Stopped the Auto Lock workflow.",
        "auto_lock_log_no_candidate": "No lockpoint candidates are available yet. Waiting for the next scan result.",
        "auto_lock_log_scan_required": "Scan is disabled and automatic SC enable is off, so candidate search cannot continue.",
        "auto_lock_log_enable_scan": "Scan is disabled. Enabling SC automatically so the search can continue.",
        "auto_lock_log_disable_lock": "Lock is currently enabled. Disabling the active lock before reacquiring.",
        "auto_lock_log_candidate_mode": "Temporarily disabling Lock Without Lockpoint so candidate points can be read.",
        "auto_lock_log_select_target": "Selected candidate lockpoint: X={x:.6f}, Y={y:.6f}.",
        "auto_lock_log_click_target": "Selected the target lockpoint from the scope plot: X={x:.6f}, Y={y:.6f}.",
        "auto_lock_log_enable_center_lock": "Switching to Lock Without Lockpoint and preparing to move the target to the center.",
        "auto_lock_log_move_offset": "Moving Scan Offset to the target lockpoint position: {x:.6f}.",
        "auto_lock_log_enable_lock": "Target is centered. Enabling Lock and waiting for DLC pro to reach the lockpoint before the PID(s) switch on.",
        "auto_lock_log_lock_waiting": "Still waiting for Locked. Current raw state is {state}.",
        "auto_lock_log_lock_success": "The device entered the Locked state. Auto Lock succeeded.",
        "auto_lock_log_monitor_lost": "Lock was lost. Preparing to search for the lockpoint again.",
        "auto_lock_log_lock_timeout": "Lock timeout expired before the device reached Locked. Reacquiring now.",
        "auto_lock_log_retry_after_disable": "The previous lock state has been cleared. Candidate search will restart shortly.",
        "auto_lock_log_scope_xy": "Switched the device Scope to XY mode so the lockpoint overlays can be displayed.",
        "auto_lock_log_scope_variant": "Switched the device Scope to {mode} mode.",
        "auto_lock_log_pre_scan_started": "Started the pre-scan workflow: keep the current scan amplitude at {amplitude:.6f} and narrow it automatically after {duration_ms} ms.",
        "auto_lock_log_pre_scan_running": "Pre-scan is running at scan amplitude {amplitude:.6f}. The range will narrow after {duration_ms} ms.",
        "auto_lock_log_pre_scan_narrowing": "Narrowing the scan range now: changing Scan Amplitude from {initial:.6f} to {target:.6f}.",
        "auto_lock_log_pre_scan_complete": "Pre-scan workflow completed. Scan Amplitude has been narrowed to {target:.6f}.",
        "auto_lock_log_pre_scan_stopped": "The pre-scan workflow has been stopped.",
        "auto_lock_log_template_start": "Starting preset {index}: wide scan amplitude {wide:.6f}, narrow scan amplitude {narrow:.6f}.",
        "auto_lock_log_template_running": "Preset {index} wide scan is running at scan amplitude {amplitude:.6f} for {duration_ms} ms before narrowing.",
        "auto_lock_log_template_narrowing": "Preset {index} is narrowing the scan range now: changing Scan Amplitude from {initial:.6f} to {target:.6f}.",
        "auto_lock_log_retry_template": "The current preset did not lock. Switching from preset {previous} to preset {current}.",
        "auto_lock_log_no_candidate_advance": "No lockpoint candidates were found repeatedly for the current preset. Switching to the next preset.",
        "auto_lock_log_templates_exhausted": "All fixed presets have been tried. Auto Lock V1 has finished.",
        "auto_lock_preset_name_required": "Enter a preset name before saving.",
        "auto_lock_preset_save_failed": "Failed to save the preset. Check write access to the current workspace.",
        "auto_lock_preset_save_requires_existing": "No existing preset is selected. Create one with \"New Preset\" first, then use \"Save Preset\" to update it.",
        "auto_lock_preset_name_exists": "A preset named {name} already exists. Use another name, or select that preset first.",
        "auto_lock_preset_created": "Created a new Auto Lock preset: {name}.",
        "auto_lock_preset_deleted": "Deleted the Auto Lock preset: {name}.",
        "auto_lock_preset_saved": "Saved Auto Lock preset: {name}.",
        "auto_lock_preset_loaded": "Loaded Auto Lock preset: {name}.",
        "auto_lock_preset_apply_busy": "Preset {name} was loaded into the UI, but the device is busy so the live link settings were not written yet.",
        "auto_lock_preset_delete_requires_selection": "Select a preset before trying to delete it.",
        "auto_lock_preset_delete_confirm_title": "Delete Preset",
        "auto_lock_preset_delete_confirm_body": "Delete preset {name}? This will remove it from the local preset file.",
        "auto_lock_preset_switch_confirm_title": "Switch Preset",
        "auto_lock_preset_switch_confirm_body": "Switch to preset {name}? The current Auto Lock settings in the UI will be overwritten by that preset.",
        "auto_lock_preset_create_success_title": "Preset Created",
        "auto_lock_preset_delete_success_title": "Preset Deleted",
        "auto_lock_preset_save_success_title": "Preset Saved",
        "auto_lock_preset_load_success_title": "Preset Switched",
        "auto_lock_warning_not_connected": "The device is not connected, so Auto Lock cannot be started.",
        "auto_lock_warning_busy": "Another device task is still running. Please wait before starting Auto Lock.",
        "auto_lock_warning_scan_amplitude_zero": "The current Scan Amplitude is 0, so the pre-scan workflow cannot run. Set a non-zero scan amplitude first.",
    }
)


TEXT["zh"].update(
    {
        "auto_lock2": "自动锁频2",
        "auto_lock2_title": "自动锁频2 - Scan Offset / Amplitude",
        "auto_lock2_status": "状态",
        "auto_lock2_acquisition": "采集源",
        "auto_lock2_waveform": "实时波形",
        "auto_lock2_controls": "控制",
        "auto_lock2_source": "采集类型",
        "auto_lock2_source_tektronix": "Tektronix/MSO64B",
        "auto_lock2_source_daq": "DAQ 预留",
        "auto_lock2_resource": "资源地址",
        "auto_lock2_transmission_channel": "透射峰通道",
        "auto_lock2_error_channel": "误差信号通道",
        "auto_lock2_points": "采样点数",
        "auto_lock2_timeout": "超时 ms",
        "auto_lock2_refresh_interval": "刷新间隔 ms",
        "auto_lock2_connect_acq": "连接采集",
        "auto_lock2_disconnect_acq": "断开采集",
        "auto_lock2_start_preview": "开始波形",
        "auto_lock2_stop_preview": "停止波形",
        "auto_lock2_one_click": "一键锁频",
        "auto_lock2_stop": "停止",
        "auto_lock2_algorithm_config": "算法配置",
        "auto_lock2_falc_settings": "FALC 设置",
        "auto_lock2_log": "日志",
        "auto_lock2_log_title": "自动锁频2 日志",
        "auto_lock2_clear_log": "清空日志",
        "auto_lock2_phase": "阶段",
        "auto_lock2_acq_status": "采集状态",
        "auto_lock2_scan_offset": "Scan Offset",
        "auto_lock2_scan_amplitude": "Scan Amplitude",
        "auto_lock2_falc_path": "FALC Path",
        "auto_lock2_confidence": "判断",
        "auto_lock2_connected": "已连接",
        "auto_lock2_disconnected": "未连接",
        "auto_lock2_waiting_frame": "等待采集帧",
        "auto_lock2_transmission": "透射峰",
        "auto_lock2_error": "误差信号",
        "auto_lock2_peak": "峰",
        "auto_lock2_zero": "误差零点",
        "auto_lock2_phase_idle": "空闲",
        "auto_lock2_phase_connecting_acquisition": "连接采集",
        "auto_lock2_phase_prepare": "准备扫描",
        "auto_lock2_phase_coarse_search": "粗搜索",
        "auto_lock2_phase_center_peak": "居中目标信号",
        "auto_lock2_phase_verify_shrink": "缩小扫频验证",
        "auto_lock2_phase_recover_peak": "锁点恢复",
        "auto_lock2_phase_ready": "Ready for FALC",
        "auto_lock2_phase_enable_falc": "使能 FALC",
        "auto_lock2_phase_locked": "完成",
        "auto_lock2_strategy_hybrid": "透射峰粗找 + 误差信号精调",
        "auto_lock2_strategy_transmission": "透射峰全过程主导",
        "auto_lock2_strategy_error": "误差信号全过程主导",
        "auto_lock2_config_strategy": "算法模式",
        "auto_lock2_config_strategy_group": "算法策略",
        "auto_lock2_config_group_common": "公共参数",
        "auto_lock2_config_group_transmission": "透射峰参数",
        "auto_lock2_config_group_error": "误差信号参数",
        "auto_lock2_config_group_protection": "双信号保护参数",
        "auto_lock2_role_common": "通用",
        "auto_lock2_role_primary": "主控",
        "auto_lock2_role_secondary": "辅助",
        "auto_lock2_role_guard": "保护",
        "auto_lock2_role_unused": "未用",
        "auto_lock2_help_current_role": "当前模式下的参数角色",
        "auto_lock2_role_common_hint": "通用：所有算法模式都会用到的流程参数，例如粗扫幅度、最小幅度、缩小比例、Offset 步长、稳定帧数。",
        "auto_lock2_role_primary_hint": "主控：当前算法主要依赖这个参数做搜索、居中或 Ready 判断。调它会直接改变算法的主要行为。",
        "auto_lock2_role_secondary_hint": "辅助：当前算法会参考这个参数，但它不是主要搜索目标。调它通常影响切换阶段或最终确认的严格程度。",
        "auto_lock2_role_guard_hint": "保护：用于交叉验证，防止假峰、假零点、噪声毛刺或采样不同步导致误判。",
        "auto_lock2_role_unused_hint": "未用：当前算法模式基本不使用这个参数；保留它是为了切换到其它算法模式时直接复用。",
        "auto_lock2_config_wide_amplitude": "粗扫幅度",
        "auto_lock2_config_min_amplitude": "最小扫频幅度",
        "auto_lock2_config_shrink_factor": "缩小比例",
        "auto_lock2_config_offset_step": "Offset 搜索步进",
        "auto_lock2_config_peak_center_tolerance": "透射峰居中容差",
        "auto_lock2_config_zero_center_tolerance": "误差零点居中容差",
        "auto_lock2_config_transmission_guard_tolerance": "透射峰保护容差",
        "auto_lock2_config_error_slope_sigma": "误差斜率 sigma",
        "auto_lock2_config_min_error_slope": "最小误差斜率",
        "auto_lock2_config_transmission_peak_sigma": "透射峰阈值 sigma",
        "auto_lock2_config_min_transmission_prominence": "最小透射峰突出量",
        "auto_lock2_config_stable_frames": "稳定帧数",
        "auto_lock2_config_max_attempts": "最大 Offset 尝试",
        "auto_lock2_config_correction_gain": "Offset 修正增益",
        "auto_lock2_config_help_title": "算法参数说明",
        "auto_lock2_preset_group": "算法配置预设",
        "auto_lock2_preset_select": "已保存配置",
        "auto_lock2_preset_loaded": "当前加载",
        "auto_lock2_preset_name": "配置名称",
        "auto_lock2_preset_new": "新建配置",
        "auto_lock2_preset_load": "加载/切换配置",
        "auto_lock2_preset_save": "保存配置",
        "auto_lock2_preset_delete": "删除配置",
        "auto_lock2_preset_none": "未选择",
        "auto_lock2_preset_default_name": "算法配置",
        "auto_lock2_preset_name_required": "请先输入配置名称再保存。",
        "auto_lock2_preset_name_exists": "配置 {name} 已存在。请换一个名字，或先选择该配置再覆盖保存。",
        "auto_lock2_preset_save_failed": "配置保存失败，请检查当前目录写入权限。",
        "auto_lock2_preset_saved_title": "配置已保存",
        "auto_lock2_preset_saved": "已保存算法配置：{name}。",
        "auto_lock2_preset_loaded_title": "配置已加载",
        "auto_lock2_preset_loaded": "已加载并切换到算法配置：{name}。",
        "auto_lock2_preset_deleted_title": "配置已删除",
        "auto_lock2_preset_deleted": "已删除算法配置：{name}。",
        "auto_lock2_preset_load_confirm_title": "切换算法配置",
        "auto_lock2_preset_load_confirm_body": "确认加载配置 {name} 吗？当前算法配置页里的参数会被覆盖，并立即同步到自动锁频2。",
        "auto_lock2_preset_delete_confirm_title": "删除算法配置",
        "auto_lock2_preset_delete_confirm_body": "确认删除配置 {name} 吗？这个操作会从本地文件里移除它。",
        "auto_lock2_config_strategy_help": "选择自动锁频2使用的判断策略。\n\n角色说明：\n通用 = 所有模式都会使用的流程参数。\n主控 = 当前模式主要依赖它完成搜索、居中或 Ready 判断。\n辅助 = 当前模式会参考它，但不是主要搜索目标。\n保护 = 用来交叉验证，防止假峰、假零点或噪声毛刺误判。\n未用 = 当前模式基本不用，保留给切换其它模式时复用。\n\n透射峰全过程主导：先找 transmission peak，并用 peak_fraction 把透射峰调到扫描中心；逐步缩小 Scan Amplitude 后继续以透射峰稳定性为主，最后用 error zero + slope 判断是否 Ready for FALC。\n\n误差信号全过程主导：先找 PDH error zero，并用 zero_fraction 把零点调到扫描中心；transmission peak 只作为附近必须有腔峰的保护条件。适合误差信号非常干净、零交叉和斜率都稳定的情况。\n\n透射峰粗找 + 误差信号精调：粗找阶段用 transmission peak 确认扫到腔共振；找到峰后转入 error zero 居中和缩幅；最终同时要求误差信号 Ready 和透射峰保护通过。",
        "auto_lock2_config_wide_amplitude_help": "启动自动锁频时写入的粗扫 Scan Amplitude。\n\n算法内部按扫频窗口理解：scan_window ≈ Scan Offset ± Scan Amplitude / 2。启动时：current_amplitude = wide_amplitude。\n\n调大：更容易覆盖远处共振峰，但一次扫到的结构更多，假峰风险和收敛时间增加。\n调小：更快、更干净，但如果 Scan Offset 离共振太远，可能整屏看不到峰。",
        "auto_lock2_config_min_amplitude_help": "允许缩小到的最小 Scan Amplitude，也是算法准备接 FALC 前的扫频下限。\n\n缩幅公式：next_amplitude = max(min_amplitude, current_amplitude * shrink_factor)。当 current_amplitude <= min_amplitude 且 Ready 条件满足，才进入关闭 Scan / 使能 FALC 的阶段。\n\n调小：锁点定位更细，但峰更容易在缩幅后消失。\n调大：更稳，但接 FALC 前扫频范围仍然较宽。",
        "auto_lock2_config_shrink_factor_help": "每次通过稳定判断后缩小 Scan Amplitude 的比例。\n\n公式：next_amplitude = max(min_amplitude, current_amplitude * shrink_factor)。例如 current=1.0 Vpp、shrink=0.65，则下一步约为 0.65 Vpp。\n\n调大到接近 1：缩小更慢、更安全。\n调小：收敛更快，但可能一下缩过头，导致透射峰或误差信号零点消失。",
        "auto_lock2_config_offset_step_help": "粗搜索和小幅探测时移动 Scan Offset 的基础步长。\n\n粗找序列近似为：offset_n = offset_0 + direction_n * ceil(n / 2) * offset_step，其中 direction_n 按 +、-、+、- 对称扩展。响应探测时也会用这个量级判断“Offset 改一点，峰/零点往哪边动”。\n\n调大：搜索快，但可能跨过窄峰或窄零点。\n调小：更细、更像实验员慢慢拧，但耗时更长。",
        "auto_lock2_config_peak_center_tolerance_help": "判断透射峰是否位于扫描周期中心附近的容差。\n\n程序把一帧波形横轴归一化为 fraction：左边=0，中心=0.5，右边=1。透射峰中心误差：peak_error = peak_fraction - 0.5。通过条件：abs(peak_error) <= peak_center_tolerance。\n\n调小：透射峰必须更靠近屏幕中心才继续。\n调大：更容易进入下一步，但峰可能还没真正居中。",
        "auto_lock2_config_zero_center_tolerance_help": "判断误差信号零交叉是否位于扫描周期中心附近的容差。\n\n归一化横轴同样是 fraction。零点中心误差：zero_error = zero_fraction - 0.5。通过条件：abs(zero_error) <= zero_center_tolerance。\n\n调小：对 PDH 锁点位置要求更严格，适合最后接 FALC 前确认。\n调大：更容易通过，但可能零点没有真正调到扫描中心。",
        "auto_lock2_config_transmission_guard_tolerance_help": "误差信号零点和透射峰之间允许相差多远。它是“双信号保护”参数，防止只看到一个噪声零点就误认为可以锁。\n\n公式：guard_distance = abs(zero_fraction - peak_fraction)。通过条件：guard_distance <= transmission_guard_tolerance。\n\n调小：要求峰和零点几乎重合，抗假零点能力更强。\n调大：能容忍探测链路延迟、滤波相位差或采样不同步，但误判风险也更高。",
        "auto_lock2_config_error_slope_sigma_help": "误差信号零点斜率的噪声倍率阈值。这里的 sigma 表示“相对于噪声的倍数”，不是 DLC pro 的硬件参数。\n\n程序估计误差信号导数噪声：d_error[i] = (error[i+1] - error[i]) * (N - 1)，slope_noise = MAD(d_error) * 1.4826。斜率阈值：slope_threshold = max(min_error_slope, error_slope_sigma * slope_noise)。通过条件：zero_slope >= slope_threshold。\n\n调大：只有更陡、更清楚的 PDH 零点才通过。\n调小：弱误差信号更容易通过，但平坦噪声也更容易被当成零点。",
        "auto_lock2_config_min_error_slope_help": "误差信号零点的绝对最小斜率，用来防止噪声估计太小时阈值变得过低。\n\n它和 sigma 阈值共同决定最终阈值：slope_threshold = max(min_error_slope, error_slope_sigma * slope_noise)。通过条件：zero_slope >= slope_threshold。\n\n调大：更严格，适合信号幅度大、PDH 斜率清楚时。\n调小：适合光电信号幅度较小的情况，但要小心噪声误判。",
        "auto_lock2_config_transmission_peak_sigma_help": "透射峰高度相对噪声的倍率阈值。这里的 sigma 表示“背景噪声的倍数”。\n\n程序估计：baseline = median(transmission)，noise = MAD(transmission) * 1.4826，peak_prominence = max(transmission) - baseline。峰阈值：peak_threshold = max(min_transmission_prominence, transmission_peak_sigma * noise)。通过条件：peak_prominence >= peak_threshold。\n\n调大：只接受很明显的腔透射峰。\n调小：弱峰也能通过，但小毛刺或干涉噪声更可能被误认为峰。",
        "auto_lock2_config_min_transmission_prominence_help": "透射峰相对基线的绝对最小突出量。它防止在低噪声情况下，因为 sigma 阈值太低而把小毛刺当成腔峰。\n\n公式：peak_prominence = max(transmission) - median(transmission)。最终峰阈值：peak_threshold = max(min_transmission_prominence, transmission_peak_sigma * noise)。通过条件：peak_prominence >= peak_threshold。\n\n探测器增益、示波器量程、采集卡量程改变后，这个参数通常需要重新检查。",
        "auto_lock2_config_stable_frames_help": "连续多少帧满足当前阶段条件后才允许进入下一步。\n\n计数逻辑：如果当前帧满足条件，stable_count = stable_count + 1；如果失败，stable_count = 0。通过条件：stable_count >= stable_frames。\n\n调大：更稳，能过滤单帧噪声或偶发毛刺，但锁定更慢。\n调小：动作更快，但更容易被一帧偶然信号误导。",
        "auto_lock2_config_max_attempts_help": "粗搜索阶段最多移动 Scan Offset 的次数。\n\n搜索范围近似：max_span ≈ ceil(max_offset_attempts / 2) * offset_step。到达次数上限仍找不到峰或有效零点时，算法停止并写入日志。\n\n调大：搜索范围更宽，但耗时更长。\n调小：失败更快，适合已知 Offset 离锁点不远的场景。",
        "auto_lock2_config_correction_gain_help": "根据峰或误差零点偏离中心计算 Scan Offset 修正量时使用的比例系数。\n\n中心误差：center_error = feature_fraction - 0.5。若已测得响应 response = delta_feature_fraction / delta_offset，则 correction ≈ -center_error / response。程序会限幅：limited_correction = clamp(correction, -2 * offset_step, 2 * offset_step)，最终写入：next_offset = current_offset + offset_correction_gain * limited_correction。\n\n调大：居中更快，但可能过冲来回摆。\n调小：动作更温和，但需要更多帧。",
        "auto_lock2_warn_dlc_not_connected": "DLC pro 未连接，不能启动自动锁频2。",
        "auto_lock2_warn_acq_not_connected": "采集源未连接，不能启动自动锁频2。",
        "auto_lock2_warn_old_autolock_running": "旧自动锁频正在运行，请先停止旧流程。",
    }
)

TEXT["en"].update(
    {
        "auto_lock2": "Auto Lock 2",
        "auto_lock2_title": "Auto Lock 2 - Scan Offset / Amplitude",
        "auto_lock2_status": "Status",
        "auto_lock2_acquisition": "Acquisition Source",
        "auto_lock2_waveform": "Live Waveform",
        "auto_lock2_controls": "Controls",
        "auto_lock2_source": "Source Type",
        "auto_lock2_source_tektronix": "Tektronix/MSO64B",
        "auto_lock2_source_daq": "DAQ Reserved",
        "auto_lock2_resource": "Resource",
        "auto_lock2_transmission_channel": "Transmission Channel",
        "auto_lock2_error_channel": "Error Channel",
        "auto_lock2_points": "Sample Points",
        "auto_lock2_timeout": "Timeout ms",
        "auto_lock2_refresh_interval": "Refresh Interval ms",
        "auto_lock2_connect_acq": "Connect Acquisition",
        "auto_lock2_disconnect_acq": "Disconnect Acquisition",
        "auto_lock2_start_preview": "Start Waveform",
        "auto_lock2_stop_preview": "Stop Waveform",
        "auto_lock2_one_click": "One-click Lock",
        "auto_lock2_stop": "Stop",
        "auto_lock2_algorithm_config": "Algorithm Config",
        "auto_lock2_falc_settings": "FALC Settings",
        "auto_lock2_log": "Log",
        "auto_lock2_log_title": "Auto Lock 2 Log",
        "auto_lock2_clear_log": "Clear Log",
        "auto_lock2_phase": "Phase",
        "auto_lock2_acq_status": "Acquisition Status",
        "auto_lock2_scan_offset": "Scan Offset",
        "auto_lock2_scan_amplitude": "Scan Amplitude",
        "auto_lock2_falc_path": "FALC Path",
        "auto_lock2_confidence": "Decision",
        "auto_lock2_connected": "Connected",
        "auto_lock2_disconnected": "Disconnected",
        "auto_lock2_waiting_frame": "Waiting for signal frame",
        "auto_lock2_transmission": "Transmission",
        "auto_lock2_error": "Error Signal",
        "auto_lock2_peak": "Peak",
        "auto_lock2_zero": "Error Zero",
        "auto_lock2_phase_idle": "Idle",
        "auto_lock2_phase_connecting_acquisition": "Connecting acquisition",
        "auto_lock2_phase_prepare": "Preparing scan",
        "auto_lock2_phase_coarse_search": "Coarse search",
        "auto_lock2_phase_center_peak": "Centering target signal",
        "auto_lock2_phase_verify_shrink": "Narrow scan verify",
        "auto_lock2_phase_recover_peak": "Recovering lock point",
        "auto_lock2_phase_ready": "Ready for FALC",
        "auto_lock2_phase_enable_falc": "Enabling FALC",
        "auto_lock2_phase_locked": "Complete",
        "auto_lock2_strategy_hybrid": "Transmission Coarse + Error Fine",
        "auto_lock2_strategy_transmission": "Transmission Primary",
        "auto_lock2_strategy_error": "Error Primary",
        "auto_lock2_config_strategy": "Algorithm Mode",
        "auto_lock2_config_strategy_group": "Algorithm Strategy",
        "auto_lock2_config_group_common": "Common Parameters",
        "auto_lock2_config_group_transmission": "Transmission Parameters",
        "auto_lock2_config_group_error": "Error Signal Parameters",
        "auto_lock2_config_group_protection": "Dual-Signal Guard Parameters",
        "auto_lock2_role_common": "Common",
        "auto_lock2_role_primary": "Primary",
        "auto_lock2_role_secondary": "Aux",
        "auto_lock2_role_guard": "Guard",
        "auto_lock2_role_unused": "Unused",
        "auto_lock2_help_current_role": "Parameter role in the current mode",
        "auto_lock2_role_common_hint": "Common: workflow parameter used by every algorithm mode, such as wide amplitude, minimum amplitude, shrink factor, Offset step, and stable frames.",
        "auto_lock2_role_primary_hint": "Primary: the selected mode mainly relies on this parameter for search, centering, or Ready decisions. Changing it directly changes the main algorithm behavior.",
        "auto_lock2_role_secondary_hint": "Auxiliary: the selected mode uses this parameter, but not as the main search target. It usually affects phase switching or final confirmation strictness.",
        "auto_lock2_role_guard_hint": "Guard: cross-check parameter used to reject false peaks, false zero crossings, noise spikes, or sampling mismatch.",
        "auto_lock2_role_unused_hint": "Unused: mostly unused by the selected mode; it remains available when switching to another algorithm mode.",
        "auto_lock2_config_wide_amplitude": "Wide Scan Amplitude",
        "auto_lock2_config_min_amplitude": "Minimum Scan Amplitude",
        "auto_lock2_config_shrink_factor": "Shrink Factor",
        "auto_lock2_config_offset_step": "Offset Search Step",
        "auto_lock2_config_peak_center_tolerance": "Peak Center Tolerance",
        "auto_lock2_config_zero_center_tolerance": "Error Zero Center Tolerance",
        "auto_lock2_config_transmission_guard_tolerance": "Transmission Guard Tolerance",
        "auto_lock2_config_error_slope_sigma": "Error Slope Sigma",
        "auto_lock2_config_min_error_slope": "Minimum Error Slope",
        "auto_lock2_config_transmission_peak_sigma": "Transmission Peak Sigma",
        "auto_lock2_config_min_transmission_prominence": "Minimum Transmission Prominence",
        "auto_lock2_config_stable_frames": "Stable Frames",
        "auto_lock2_config_max_attempts": "Max Offset Attempts",
        "auto_lock2_config_correction_gain": "Offset Correction Gain",
        "auto_lock2_config_help_title": "Algorithm Parameter Help",
        "auto_lock2_preset_group": "Algorithm Config Presets",
        "auto_lock2_preset_select": "Saved Config",
        "auto_lock2_preset_loaded": "Loaded Config",
        "auto_lock2_preset_name": "Config Name",
        "auto_lock2_preset_new": "New Config",
        "auto_lock2_preset_load": "Load / Switch Config",
        "auto_lock2_preset_save": "Save Config",
        "auto_lock2_preset_delete": "Delete Config",
        "auto_lock2_preset_none": "None",
        "auto_lock2_preset_default_name": "Algorithm Config",
        "auto_lock2_preset_name_required": "Enter a config name before saving.",
        "auto_lock2_preset_name_exists": "Config {name} already exists. Use another name, or select it before overwriting.",
        "auto_lock2_preset_save_failed": "Failed to save the config. Check write access to the current workspace.",
        "auto_lock2_preset_saved_title": "Config Saved",
        "auto_lock2_preset_saved": "Saved algorithm config: {name}.",
        "auto_lock2_preset_loaded_title": "Config Loaded",
        "auto_lock2_preset_loaded": "Loaded and switched to algorithm config: {name}.",
        "auto_lock2_preset_deleted_title": "Config Deleted",
        "auto_lock2_preset_deleted": "Deleted algorithm config: {name}.",
        "auto_lock2_preset_load_confirm_title": "Switch Algorithm Config",
        "auto_lock2_preset_load_confirm_body": "Load config {name}? The current Algorithm Config values will be overwritten and applied to Auto Lock 2 immediately.",
        "auto_lock2_preset_delete_confirm_title": "Delete Algorithm Config",
        "auto_lock2_preset_delete_confirm_body": "Delete config {name}? This removes it from the local preset file.",
        "auto_lock2_config_strategy_help": "Select which Auto Lock 2 decision strategy to use.\n\nRole legend:\nCommon = workflow parameter used by every mode.\nPrimary = the selected mode mainly uses it for search, centering, or Ready decisions.\nAuxiliary = used by the selected mode, but not as the main search target.\nGuard = cross-check used to reject false peaks, false zero crossings, or noise spikes.\nUnused = mostly unused in the selected mode, but kept for other modes.\n\nTransmission Primary: finds the transmission peak first and uses peak_fraction to center the peak. While narrowing Scan Amplitude, it still primarily checks peak stability, then uses error zero + slope as the final Ready-for-FALC confirmation.\n\nError Primary: finds the PDH error zero first and uses zero_fraction to center it. The transmission peak is only a protection condition requiring a nearby cavity peak. This works best when the PDH error signal is clean and stable.\n\nTransmission Coarse + Error Fine: uses transmission during coarse search to confirm cavity resonance, then switches to error-zero centering and scan narrowing. Final Ready requires both error readiness and transmission protection.",
        "auto_lock2_config_wide_amplitude_help": "Wide Scan Amplitude written at the start of Auto Lock 2.\n\nInternal scan-window model: scan_window ~= Scan Offset +/- Scan Amplitude / 2. At start: current_amplitude = wide_amplitude.\n\nLarger: covers farther resonances but creates more complex waveforms and more false-peak risk.\nSmaller: faster and cleaner, but may miss the cavity peak if Scan Offset is too far away.",
        "auto_lock2_config_min_amplitude_help": "Lower limit for Scan Amplitude before the algorithm can hand over to FALC.\n\nNarrowing formula: next_amplitude = max(min_amplitude, current_amplitude * shrink_factor). When current_amplitude <= min_amplitude and Ready checks pass, the controller can stop Scan and enable FALC.\n\nSmaller: finer lock-point localization but easier to lose the feature.\nLarger: safer, but leaves a wider scan before FALC.",
        "auto_lock2_config_shrink_factor_help": "Multiplier applied when narrowing Scan Amplitude after stable checks.\n\nFormula: next_amplitude = max(min_amplitude, current_amplitude * shrink_factor). Example: current=1.0 Vpp and shrink=0.65 gives about 0.65 Vpp.\n\nCloser to 1: slower and safer.\nSmaller: faster convergence, but may shrink past the peak or zero crossing.",
        "auto_lock2_config_offset_step_help": "Base step used when moving Scan Offset during coarse search and small response probes.\n\nCoarse search sequence is approximately: offset_n = offset_0 + direction_n * ceil(n / 2) * offset_step, with direction_n alternating +, -, +, -. Probes use the same order of magnitude to learn how a feature moves when Offset changes.\n\nLarger: faster search but may skip narrow features.\nSmaller: slower but more like careful manual tuning.",
        "auto_lock2_config_peak_center_tolerance_help": "Tolerance for deciding whether the transmission peak is close enough to the scan-frame center.\n\nThe frame x-axis is normalized as fraction: left=0, center=0.5, right=1. Peak center error: peak_error = peak_fraction - 0.5. Pass condition: abs(peak_error) <= peak_center_tolerance.\n\nSmaller: stricter centering.\nLarger: advances sooner, but may leave the peak off-center.",
        "auto_lock2_config_zero_center_tolerance_help": "Tolerance for deciding whether the PDH error zero crossing is close enough to the scan-frame center.\n\nThe normalized x-axis uses fraction. Zero center error: zero_error = zero_fraction - 0.5. Pass condition: abs(zero_error) <= zero_center_tolerance.\n\nSmaller: stricter and better before FALC handoff.\nLarger: easier to pass, but the zero may not be centered.",
        "auto_lock2_config_transmission_guard_tolerance_help": "Allowed distance between the error zero and the transmission peak. This is the two-signal guard that prevents a random noise zero from being accepted as a lock point.\n\nFormula: guard_distance = abs(zero_fraction - peak_fraction). Pass condition: guard_distance <= transmission_guard_tolerance.\n\nSmaller: stronger false-zero rejection.\nLarger: tolerates detector delay, filter phase shift, or acquisition skew, but raises false-ready risk.",
        "auto_lock2_config_error_slope_sigma_help": "Noise-multiple threshold for the error-signal zero-crossing slope. Here sigma means a multiplier of estimated noise, not a DLC pro hardware setting.\n\nDerivative noise estimate: d_error[i] = (error[i+1] - error[i]) * (N - 1), slope_noise = MAD(d_error) * 1.4826. Slope threshold: slope_threshold = max(min_error_slope, error_slope_sigma * slope_noise). Pass condition: zero_slope >= slope_threshold.\n\nLarger: accepts only steeper, cleaner PDH zero crossings.\nSmaller: catches weaker PDH signals but can accept flat noise.",
        "auto_lock2_config_min_error_slope_help": "Absolute lower bound for the error-zero slope threshold. It prevents the sigma threshold from becoming too low when estimated noise is tiny.\n\nFinal threshold: slope_threshold = max(min_error_slope, error_slope_sigma * slope_noise). Pass condition: zero_slope >= slope_threshold.\n\nLarger: stricter, useful when signal amplitude is large.\nSmaller: useful with weak detector signals, but increases noise risk.",
        "auto_lock2_config_transmission_peak_sigma_help": "Noise-multiple threshold for transmission peak detection. Here sigma means a multiplier of background noise.\n\nEstimate: baseline = median(transmission), noise = MAD(transmission) * 1.4826, peak_prominence = max(transmission) - baseline. Peak threshold: peak_threshold = max(min_transmission_prominence, transmission_peak_sigma * noise). Pass condition: peak_prominence >= peak_threshold.\n\nLarger: accepts only clearer cavity peaks.\nSmaller: lets weak peaks pass, but may accept spikes or interference noise.",
        "auto_lock2_config_min_transmission_prominence_help": "Absolute minimum peak height above baseline. It prevents tiny spikes from passing when the sigma threshold is low.\n\nFormula: peak_prominence = max(transmission) - median(transmission). Final threshold: peak_threshold = max(min_transmission_prominence, transmission_peak_sigma * noise). Pass condition: peak_prominence >= peak_threshold.\n\nRe-check this after changing detector gain, oscilloscope scale, or DAQ voltage range.",
        "auto_lock2_config_stable_frames_help": "Number of consecutive frames required before advancing to the next stage.\n\nCounter rule: if the current frame passes, stable_count = stable_count + 1; otherwise stable_count = 0. Pass condition: stable_count >= stable_frames.\n\nLarger: more robust against single-frame noise, but slower.\nSmaller: faster, but more likely to react to a transient.",
        "auto_lock2_config_max_attempts_help": "Maximum number of Scan Offset moves during coarse search.\n\nApproximate search span: max_span ~= ceil(max_offset_attempts / 2) * offset_step. If the limit is reached without a valid peak or zero crossing, the algorithm stops and logs the failure.\n\nLarger: wider search but longer time.\nSmaller: fails faster, useful when Offset is already near the lock point.",
        "auto_lock2_config_correction_gain_help": "Proportional gain applied to Scan Offset correction when centering a peak or error zero.\n\nCenter error: center_error = feature_fraction - 0.5. If a measured response is available, response = delta_feature_fraction / delta_offset and correction ~= -center_error / response. The controller limits the move: limited_correction = clamp(correction, -2 * offset_step, 2 * offset_step). Final write: next_offset = current_offset + offset_correction_gain * limited_correction.\n\nLarger: centers faster but can overshoot.\nSmaller: smoother but needs more frames.",
        "auto_lock2_warn_dlc_not_connected": "DLC pro is not connected, so Auto Lock 2 cannot start.",
        "auto_lock2_warn_acq_not_connected": "The acquisition source is not connected, so Auto Lock 2 cannot start.",
        "auto_lock2_warn_old_autolock_running": "The original Auto Lock workflow is running. Stop it before using Auto Lock 2.",
    }
)
